import { ISessionItem, IStoryItem, IUnitItem } from "@/interfaces/common";
import { v4 as uuidv4 } from "uuid";

export const initialEssentialUnit: IUnitItem[] = [
  {
    id: "essentialUnit2",
    title: "Unit 2",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "essentialUnit3",
    title: "Unit 3",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "essentialUnit4",
    title: "Unit 4",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "essentialUnit5",
    title: "Unit 5",
    subtitle: "4000 Essential English Word 2",
  },
];
export const initialEssentialSession: ISessionItem[] = [
  {
    id: "essentialSession2",
    unitId: "essentialUnit2",
    title: "Story 2",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "essentialSession3",
    unitId: "essentialUnit2",
    title: "Story 3",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "essentialSession4",
    unitId: "essentialUnit2",
    title: "Story 4",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "essentialSession5",
    unitId: "essentialUnit2",
    title: "Story 5",
    subtitle: "4000 Essential English Word 2",
  },
];
export const initialEssentialStoryEn: IStoryItem[] = [
  {
    id: "1",
    sessionId: "essentialSession2",
    en: "abandon",
    vn: "bỏ rơi",
  },
  {
    id: "2",
    sessionId: "essentialSession2",
    en: "accompany",
    vn: "đi cùng",
  },
  {
    id: "3",
    sessionId: "essentialSession2",
    en: "accused",
    vn: "buộc tội",
  },
  {
    id: "4",
    sessionId: "essentialSession2",
    en: "adopted",
    vn: "nhận nuôi",
  },
  {
    id: "5",
    sessionId: "essentialSession2",
    en: "affection",
    vn: "sự yêu mến",
  },
  {
    id: "6",
    sessionId: "essentialSession2",
    en: "affirm",
    vn: "khẳng định",
  },
  {
    id: "7",
    sessionId: "essentialSession2",
    en: "altered",
    vn: "thay đổi",
  },
  {
    id: "8",
    sessionId: "essentialSession2",
    en: "amuse someone",
    vn: "làm vui ai đó",
  },
  {
    id: "9",
    sessionId: "essentialSession2",
    en: "anticipate",
    vn: "mong đợi",
  },
  {
    id: "10",
    sessionId: "essentialSession2",
    en: "arrest",
    vn: "ngăn chặn",
  },
  {
    id: "11",
    sessionId: "essentialSession2",
    en: "attach",
    vn: "gắn",
  },
  {
    id: "10",
    sessionId: "essentialSession2",
    en: "attempt",
    vn: "nỗ lực",
  },
  {
    id: "10",
    sessionId: "essentialSession2",
    en: "attain",
    vn: "đặt được",
  },
  {
    id: "11",
    sessionId: "essentialSession2",
    en: "bathe",
    vn: "tắm",
  },
  {
    id: "12",
    sessionId: "essentialSession2",
    en: "bend",
    vn: "uốn cong",
  },
  {
    id: "13",
    sessionId: "essentialSession2",
    en: "bet",
    vn: "đặt",
  },
  {
    id: "14",
    sessionId: "essentialSession2",
    en: "bite",
    vn: "cắn",
  },
  {
    id: "15",
    sessionId: "essentialSession2",
    en: "blame",
    vn: "đổ lỗi",
  },
  {
    id: "16",
    sessionId: "essentialSession2",
    en: "bless",
    vn: "ban phước",
  },
  {
    id: "17",
    sessionId: "essentialSession2",
    en: "bounce ideas",
    vn: "nảy ý tưởng",
  },
  {
    id: "18",
    sessionId: "essentialSession2",
    en: "brag",
    vn: "khoe",
  },
  {
    id: "19",
    sessionId: "essentialSession2",
    en: "burn",
    vn: "đốt",
  },
  {
    id: "20",
    sessionId: "essentialSession2",
    en: "burst",
    vn: "bùng nổ",
  },
  // story 3
  {
    id: "21",
    sessionId: "essentialSession3",
    en: "appearance",
    vn: "diện mạo",
  },
  {
    id: "22",
    sessionId: "essentialSession3",
    en: "appropriate",
    vn: "phù hợp",
  },
  {
    id: "23",
    sessionId: "essentialSession3",
    en: "arise",
    vn: "nảy sinh",
  },
  {
    id: "24",
    sessionId: "essentialSession3",
    en: "arrange",
    vn: "sắp xếp",
  },
  {
    id: "25",
    sessionId: "essentialSession3",
    en: "assist",
    vn: "giúp đỡ",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession3",
    en: "authority",
    vn: "thẩm quyền(uy tín)",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession3",
    en: "basis",
    vn: "nền tảng",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession3",
    en: "beat",
    vn: "đánh bại",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession3",
    en: "bend",
    vn: "uốn cong",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession3",
    en: "blind",
    vn: "làm mù",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession3",
    en: "boast",
    vn: "khoe khoang",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession3",
    en: "brief",
    vn: "ngắn gọn(tóm tắt)",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession3",
    en: "burst",
    vn: "bùng nổ",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession3",
    en: "bury",
    vn: "chôn giấu",
  },
  // story 4
  {
    id: uuidv4(),
    sessionId: "essentialSession4",
    en: "atmosphere",
    vn: "bầu không khí",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession4",
    en: "attractive",
    vn: "hấp dẫn",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession4",
    en: "cite",
    vn: "trích dẫn",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession4",
    en: "consist of",
    vn: "bao gồm",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession4",
    en: "demonstrate",
    vn: "trình diễn",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession4",
    en: "diagonally",
    vn: "theo đường chéo",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession4",
    en: "ended up with",
    vn: "kết thúc với",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession4",
    en: "extent",
    vn: "mức độ",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession4",
    en: "factor",
    vn: "yếu tố",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession4",
    en: "humidity",
    vn: "độ ẩm",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession4",
    en: "interior",
    vn: "nội thất",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession4",
    en: "investigate",
    vn: "điều tra",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession4",
    en: "moisture",
    vn: "ẩm",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession4",
    en: "money-conscious",
    vn: "tiết kiệm",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession4",
    en: "persuade",
    vn: "thuyết phục",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession4",
    en: "printing",
    vn: "in ấn",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession4",
    en: "reasonable amount",
    vn: "mức giá hợp lý",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession4",
    en: "occasion",
    vn: "dịp",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession4",
    en: "take up space",
    vn: "chiếm không gian",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession4",
    en: "three-dimensional",
    vn: "ba chiều",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession4",
    en: "widespread",
    vn: "lan rộng",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession4",
    en: "worldwide",
    vn: "toàn cầu",
  },
  // story 5
  {
    id: uuidv4(),
    sessionId: "essentialSession5",
    en: "agricultural",
    vn: "nông nghiệp",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession5",
    en: "beehive",
    vn: "tổ ong",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession5",
    en: "brilliant",
    vn: "xuất sắc",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession5",
    en: "colony",
    vn: "thuộc địa",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession5",
    en: "come upon",
    vn: "bắt gặp",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession5",
    en: "cut off",
    vn: "cắt đứt",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession5",
    en: "distinctive",
    vn: "đặc biệt",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession5",
    en: "markings",
    vn: "dấu vết",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession5",
    en: "ecology",
    vn: "sinh thái học",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession5",
    en: "farmland",
    vn: "đất canh tác",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession5",
    en: "grassland",
    vn: "đồng cỏ",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession5",
    en: "focus efforts",
    vn: "tập trung nỗ lực vào",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession5",
    en: "harmless",
    vn: "vô hại",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession5",
    en: "hemisphere",
    vn: "bán cầu",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession5",
    en: "hostile",
    vn: "khắc nghiệt",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession5",
    en: "indicate",
    vn: "chỉ ra",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession5",
    en: "extinction",
    vn: "tuyệt chủng",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession5",
    en: "observe",
    vn: "quan sát",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession5",
    en: "patterns",
    vn: "mẫu",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession5",
    en: "poison",
    vn: "chất độc",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession5",
    en: "source of food",
    vn: "nguồn thức ăn",
  },
  {
    id: uuidv4(),
    sessionId: "essentialSession5",
    en: "underestimate",
    vn: "đánh giá thấp",
  },
];
