import { ISessionItem, IStoryItem, IUnitItem } from "@/interfaces/common";
import { v4 as uuidv4 } from "uuid";

export const initialEssentialUnit: IUnitItem[] = [
  {
    id: "book2",
    title: "4000 Essential English Word 2",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "book3",
    title: "4000 Essential English Word 3",
    subtitle: "4000 Essential English Word 3",
  },
  {
    id: "book4",
    title: "4000 Essential English Word 4",
    subtitle: "4000 Essential English Word 4",
  },
  {
    id: "book5",
    title: "4000 Essential English Word 5",
    subtitle: "4000 Essential English Word 5",
  },
  {
    id: "book6",
    title: "4000 Essential English Word 6",
    subtitle: "4000 Essential English Word 6",
  },
];
export const initialEssentialSession: ISessionItem[] = [
  {
    id: "unit2",
    unitId: "book2",
    title: "Unit 2",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit3",
    unitId: "book2",
    title: "Unit 3",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit4",
    unitId: "book2",
    title: "Unit 4",
    subtitle: "4000 Essential English Word 2",
  },

  {
    id: "unit5",
    unitId: "book2",
    title: "Unit 5",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit6",
    unitId: "book2",
    title: "Unit 6",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit7",
    unitId: "book2",
    title: "Unit 7",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit8",
    unitId: "book2",
    title: "Unit 8",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit9",
    unitId: "book2",
    title: "Unit 9",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit10",
    unitId: "book2",
    title: "Unit 10",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit11",
    unitId: "book2",
    title: "Unit 11",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit12",
    unitId: "book2",
    title: "Unit 12",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit13",
    unitId: "book2",
    title: "Unit 14",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit14",
    unitId: "book2",
    title: "Unit 14",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit15",
    unitId: "book2",
    title: "Unit 15",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit16",
    unitId: "book2",
    title: "Unit 16",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit17",
    unitId: "book2",
    title: "Unit 17",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit18",
    unitId: "book2",
    title: "Unit 18",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit19",
    unitId: "book2",
    title: "Unit 19",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit20",
    unitId: "book2",
    title: "Unit 20",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit21",
    unitId: "book2",
    title: "Unit 21",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit22",
    unitId: "book2",
    title: "Unit 22",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit23",
    unitId: "book2",
    title: "Unit 23",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit24",
    unitId: "book2",
    title: "Unit 24",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit25",
    unitId: "book2",
    title: "Unit 25",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit26",
    unitId: "book2",
    title: "Unit 26",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit27",
    unitId: "book2",
    title: "Unit 27",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit28",
    unitId: "book2",
    title: "Unit 28",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit29",
    unitId: "book2",
    title: "Unit 29",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit30",
    unitId: "book2",
    title: "Unit 30",
    subtitle: "4000 Essential English Word 2",
  },
];
export const initialEssentialStoryEn: IStoryItem[] = [
  {
    id: uuidv4(),
    sessionId: "unit2",
    en: "bring",
    vn: "mang",
    exampleVn: "... cho tôi một cái ví",
  },
  {
    id: uuidv4(),
    sessionId: "unit2",
    en: "castle",
    vn: "lâu đài",
    exampleVn: "Họ sống trong một ... cổ.",
  },
  {
    id: uuidv4(),
    sessionId: "unit2",
    en: "command",
    vn: "ra lệnh",
    exampleVn: "Anh ta ... cho binh lính tấn công.",
  },
  {
    id: uuidv4(),
    sessionId: "unit2",
    en: "counsel",
    vn: "tư vấn, khuyên nhủ",
    exampleVn: "Cô ấy luôn ... bạn bè của mình.",
  },
  {
    id: uuidv4(),
    sessionId: "unit2",
    en: "ensure",
    vn: "đảm bảo",
    exampleVn: "Hãy ... rằng cửa đã khóa.",
  },
  {
    id: uuidv4(),
    sessionId: "unit2",
    en: "explosion",
    vn: "vụ nổ",
    exampleVn: "Một ... lớn xảy ra trong nhà máy.",
  },
  {
    id: uuidv4(),
    sessionId: "unit2",
    en: "jewelry",
    vn: "trang sức",
    exampleVn: "Cô ấy đeo rất nhiều ... đắt tiền.",
  },
  {
    id: uuidv4(),
    sessionId: "unit2",
    en: "land",
    vn: "hạ cánh, đất đai",
    exampleVn: "Máy bay sẽ ... sau 10 phút.",
  },
  {
    id: uuidv4(),
    sessionId: "unit2",
    en: "meteor",
    vn: "thiên thạch",
    exampleVn: "Một ... lớn bay ngang qua bầu trời.",
  },
  {
    id: uuidv4(),
    sessionId: "unit2",
    en: "monster",
    vn: "quái vật",
    exampleVn: "Đứa trẻ sợ có ... dưới gầm giường.",
  },
  {
    id: uuidv4(),
    sessionId: "unit2",
    en: "northern",
    vn: "thuộc phía bắc",
    exampleVn: "Anh ấy đến từ vùng ... nước Anh.",
  },
  {
    id: uuidv4(),
    sessionId: "unit2",
    en: "remote",
    vn: "xa xôi, hẻo lánh",
    exampleVn: "Ngôi làng nằm ở nơi rất ....",
  },
  {
    id: uuidv4(),
    sessionId: "unit2",
    en: "southern",
    vn: "thuộc phía nam",
    exampleVn: "Cô ấy sinh ra ở vùng ... nước Ý.",
  },
  {
    id: uuidv4(),
    sessionId: "unit2",
    en: "statue",
    vn: "tượng",
    exampleVn: "Bức ... đó làm bằng đá cẩm thạch.",
  },
  {
    id: uuidv4(),
    sessionId: "unit2",
    en: "steam",
    vn: "hơi nước",
    exampleVn: "... bốc lên từ ấm trà.",
  },
  {
    id: uuidv4(),
    sessionId: "unit2",
    en: "submit",
    vn: "nộp, trình",
    exampleVn: "Hãy ... bài tập trước 5 giờ chiều.",
  },
  {
    id: uuidv4(),
    sessionId: "unit2",
    en: "temple",
    vn: "ngôi đền",
    exampleVn: "Họ đi đến ... để cầu nguyện.",
  },
  {
    id: uuidv4(),
    sessionId: "unit2",
    en: "upper",
    vn: "phía trên, cao hơn",
    exampleVn: "Phòng ngủ ở tầng ....",
  },
  {
    id: uuidv4(),
    sessionId: "unit2",
    en: "weed",
    vn: "cỏ dại",
    exampleVn: "Khu vườn đầy ....",
  },
  {
    id: uuidv4(),
    sessionId: "unit2",
    en: "wing",
    vn: "cánh",
    exampleVn: "Con chim dang rộng đôi ... và bay đi.",
  },

  {
    id: uuidv4(),
    sessionId: "unit3",
    en: "arrow",
    vn: "mũi tên",
    exampleVn: "Anh ta bắn một ... vào mục tiêu.",
  },
  {
    id: uuidv4(),
    sessionId: "unit3",
    en: "battle",
    vn: "trận chiến",
    exampleVn: "Nhiều người lính đã ngã xuống trong ... này.",
  },
  {
    id: uuidv4(),
    sessionId: "unit3",
    en: "bow",
    vn: "cái cung",
    exampleVn: "Cậu bé kéo ... và bắn trúng hồng tâm.",
  },
  {
    id: uuidv4(),
    sessionId: "unit3",
    en: "brave",
    vn: "dũng cảm",
    exampleVn: "Người lính rất ... khi đối mặt với kẻ thù.",
  },
  {
    id: uuidv4(),
    sessionId: "unit3",
    en: "chief",
    vn: "thủ lĩnh",
    exampleVn: "... của bộ tộc đưa ra quyết định cuối cùng.",
  },
  {
    id: uuidv4(),
    sessionId: "unit3",
    en: "disadvantage",
    vn: "bất lợi",
    exampleVn: "Sống ở vùng xa là một ....",
  },
  {
    id: uuidv4(),
    sessionId: "unit3",
    en: "enemy",
    vn: "kẻ thù",
    exampleVn: "Họ chiến đấu chống lại ....",
  },
  {
    id: uuidv4(),
    sessionId: "unit3",
    en: "entrance",
    vn: "lối vào",
    exampleVn: "Có hai ... chính của tòa nhà.",
  },
  {
    id: uuidv4(),
    sessionId: "unit3",
    en: "hardly",
    vn: "hầu như không",
    exampleVn: "Tôi ... hiểu được những gì anh ta nói.",
  },
  {
    id: uuidv4(),
    sessionId: "unit3",
    en: "intend",
    vn: "dự định",
    exampleVn: "Tôi ... học tiếng Anh chăm chỉ hơn.",
  },
  {
    id: uuidv4(),
    sessionId: "unit3",
    en: "laughter",
    vn: "tiếng cười",
    exampleVn: "... vang lên khắp căn phòng.",
  },
  {
    id: uuidv4(),
    sessionId: "unit3",
    en: "log",
    vn: "khúc gỗ",
    exampleVn: "Anh ta ngồi trên một ... bên bờ sông.",
  },
  {
    id: uuidv4(),
    sessionId: "unit3",
    en: "military",
    vn: "quân đội",
    exampleVn: "Anh trai tôi phục vụ trong ....",
  },
  {
    id: uuidv4(),
    sessionId: "unit3",
    en: "obey",
    vn: "vâng lời",
    exampleVn: "Trẻ em nên ... cha mẹ của mình.",
  },
  {
    id: uuidv4(),
    sessionId: "unit3",
    en: "secure",
    vn: "an toàn",
    exampleVn: "Giữ tiền của bạn ở nơi ....",
  },
  {
    id: uuidv4(),
    sessionId: "unit3",
    en: "steady",
    vn: "vững chắc",
    exampleVn: "Cầu này rất ..., bạn có thể đi qua.",
  },
  {
    id: uuidv4(),
    sessionId: "unit3",
    en: "trust",
    vn: "tin tưởng",
    exampleVn: "Tôi ... anh ấy vì anh ấy luôn giữ lời hứa.",
  },
  {
    id: uuidv4(),
    sessionId: "unit3",
    en: "twist",
    vn: "xoắn, vặn",
    exampleVn: "Anh ta ... cái nắp để mở chai nước.",
  },
  {
    id: uuidv4(),
    sessionId: "unit3",
    en: "unless",
    vn: "trừ khi",
    exampleVn: "Tôi sẽ không đi ... bạn đi cùng tôi.",
  },
  {
    id: uuidv4(),
    sessionId: "unit3",
    en: "weapon",
    vn: "vũ khí",
    exampleVn: "Cảnh sát tịch thu tất cả các ....",
  },

  {
    id: uuidv4(),
    sessionId: "unit4",
    en: "chest",
    vn: "ngực",
    exampleVn: "Anh ta bị đau ở ....",
  },
  {
    id: uuidv4(),
    sessionId: "unit4",
    en: "confidence",
    vn: "sự tự tin",
    exampleVn: "Cô ấy nói với ... trong giọng nói.",
  },
  {
    id: uuidv4(),
    sessionId: "unit4",
    en: "consequence",
    vn: "hậu quả",
    exampleVn: "Mọi hành động đều có ....",
  },
  {
    id: uuidv4(),
    sessionId: "unit4",
    en: "disaster",
    vn: "thảm họa",
    exampleVn: "Trận động đất là một ....",
  },
  {
    id: uuidv4(),
    sessionId: "unit4",
    en: "disturb",
    vn: "làm phiền",
    exampleVn: "Đừng ... tôi khi tôi đang làm việc.",
  },
  {
    id: uuidv4(),
    sessionId: "unit4",
    en: "estimate",
    vn: "ước lượng",
    exampleVn: "Tôi ... chi phí khoảng 500 đô.",
  },
  {
    id: uuidv4(),
    sessionId: "unit4",
    en: "honor",
    vn: "vinh dự, danh dự",
    exampleVn: "Thật là một ... khi được gặp ngài.",
  },
  {
    id: uuidv4(),
    sessionId: "unit4",
    en: "impress",
    vn: "gây ấn tượng",
    exampleVn: "Cô ấy cố gắng ... nhà tuyển dụng.",
  },
  {
    id: uuidv4(),
    sessionId: "unit4",
    en: "marathon",
    vn: "cuộc chạy marathon",
    exampleVn: "Anh ấy đã hoàn thành ... đầu tiên của mình.",
  },
  {
    id: uuidv4(),
    sessionId: "unit4",
    en: "narrow",
    vn: "hẹp",
    exampleVn: "Con đường này quá ....",
  },
  {
    id: uuidv4(),
    sessionId: "unit4",
    en: "pale",
    vn: "tái nhợt",
    exampleVn: "Cô ấy trông ... sau khi ốm dậy.",
  },
  {
    id: uuidv4(),
    sessionId: "unit4",
    en: "rough",
    vn: "gồ ghề, thô ráp",
    exampleVn: "Bề mặt của đá rất ....",
  },
  {
    id: uuidv4(),
    sessionId: "unit4",
    en: "satisfy",
    vn: "làm hài lòng",
    exampleVn: "Sản phẩm này chắc chắn sẽ ... bạn.",
  },
  {
    id: uuidv4(),
    sessionId: "unit4",
    en: "scream",
    vn: "thét, hét",
    exampleVn: "Cô ấy ... khi thấy con nhện.",
  },
  {
    id: uuidv4(),
    sessionId: "unit4",
    en: "sensitive",
    vn: "nhạy cảm",
    exampleVn: "Da của tôi rất ... với ánh nắng.",
  },
  {
    id: uuidv4(),
    sessionId: "unit4",
    en: "shade",
    vn: "bóng râm",
    exampleVn: "Chúng tôi ngồi dưới ... của cái cây.",
  },
  {
    id: uuidv4(),
    sessionId: "unit4",
    en: "supplement",
    vn: "bổ sung",
    exampleVn: "Cô ấy uống vitamin như một cách để ... dinh dưỡng.",
  },
  {
    id: uuidv4(),
    sessionId: "unit4",
    en: "terror",
    vn: "nỗi kinh hoàng",
    exampleVn: "Ngôi làng chìm trong ....",
  },
  {
    id: uuidv4(),
    sessionId: "unit4",
    en: "threat",
    vn: "mối đe dọa",
    exampleVn: "Ô nhiễm là một ... lớn đối với môi trường.",
  },
  {
    id: uuidv4(),
    sessionId: "unit4",
    en: "victim",
    vn: "nạn nhân",
    exampleVn: "Cảnh sát đã giúp đỡ .... của vụ tai nạn.",
  },
  {
    id: uuidv4(),
    sessionId: "unit5",
    en: "ancestor",
    vn: "tổ tiên",
    exampleVn: "... của chúng tôi rất tốt.",
  },
  {
    id: uuidv4(),
    sessionId: "unit5",
    en: "angle",
    vn: "góc",
    exampleVn: "... của hình tam giác này là 90 độ.",
  },
  {
    id: uuidv4(),
    sessionId: "unit5",
    en: "boot",
    vn: "ủng",
    exampleVn: "Tôi mang ... khi trời mưa.",
  },
  {
    id: uuidv4(),
    sessionId: "unit5",
    en: "border",
    vn: "biên giới",
    exampleVn: "Chúng tôi sống gần ... giữa hai nước.",
  },
  {
    id: uuidv4(),
    sessionId: "unit5",
    en: "congratulate",
    vn: "chúc mừng",
    exampleVn: "Tôi ... bạn đã đạt được thành công lớn.",
  },
  {
    id: uuidv4(),
    sessionId: "unit5",
    en: "frame",
    vn: "khung",
    exampleVn: "Tôi treo bức ảnh trong một ... đẹp.",
  },
  {
    id: uuidv4(),
    sessionId: "unit5",
    en: "heaven",
    vn: "thiên đường",
    exampleVn: "Nhiều người tin rằng linh hồn sẽ lên ...",
  },
  {
    id: uuidv4(),
    sessionId: "unit5",
    en: "incredible",
    vn: "khó tin, tuyệt vời",
    exampleVn: "Màn trình diễn đó thật ...!",
  },
  {
    id: uuidv4(),
    sessionId: "unit5",
    en: "legend",
    vn: "huyền thoại",
    exampleVn: "Ông ấy là một ... trong làng bóng đá.",
  },
  {
    id: uuidv4(),
    sessionId: "unit5",
    en: "praise",
    vn: "khen ngợi",
    exampleVn: "Cô giáo luôn ... học sinh chăm chỉ.",
  },
  {
    id: uuidv4(),
    sessionId: "unit5",
    en: "proceed",
    vn: "tiếp tục",
    exampleVn: "Chúng ta hãy ... công việc nhé.",
  },
  {
    id: uuidv4(),
    sessionId: "unit5",
    en: "pure",
    vn: "nguyên chất, tinh khiết",
    exampleVn: "Cô ấy có một trái tim ...",
  },
  {
    id: uuidv4(),
    sessionId: "unit5",
    en: "relative",
    vn: "họ hàng, người thân",
    exampleVn: "Tôi có nhiều ... sống ở nước ngoài.",
  },
  {
    id: uuidv4(),
    sessionId: "unit5",
    en: "senior",
    vn: "cao cấp, lớn tuổi",
    exampleVn: "Ông ấy là nhân viên ... trong công ty.",
  },
  {
    id: uuidv4(),
    sessionId: "unit5",
    en: "silent",
    vn: "im lặng",
    exampleVn: "Căn phòng trở nên ... sau khi cô ấy rời đi.",
  },
  {
    id: uuidv4(),
    sessionId: "unit5",
    en: "sink",
    vn: "chìm, bồn rửa",
    exampleVn: "Con tàu bắt đầu ... sau khi va vào đá.",
  },
  {
    id: uuidv4(),
    sessionId: "unit5",
    en: "superior",
    vn: "vượt trội, cấp trên",
    exampleVn: "Sản phẩm này có chất lượng ... hơn hẳn.",
  },
  {
    id: uuidv4(),
    sessionId: "unit5",
    en: "surround",
    vn: "bao quanh",
    exampleVn: "Ngôi làng được ... bởi rừng cây.",
  },
  {
    id: uuidv4(),
    sessionId: "unit5",
    en: "thick",
    vn: "dày",
    exampleVn: "Bức tường này rất ... và chắc chắn.",
  },
  {
    id: uuidv4(),
    sessionId: "unit5",
    en: "wrap",
    vn: "gói, bọc",
    exampleVn: "Tôi sẽ ... món quà này bằng giấy màu đỏ.",
  },
  {
    id: uuidv4(),
    sessionId: "unit6",
    en: "abroad",
    vn: "ở nước ngoài",
    exampleVn: "Tôi muốn du học ...",
  },
  {
    id: uuidv4(),
    sessionId: "unit6",
    en: "anger",
    vn: "sự tức giận",
    exampleVn: "Anh ấy không thể kiểm soát ... của mình.",
  },
  {
    id: uuidv4(),
    sessionId: "unit6",
    en: "bride",
    vn: "cô dâu",
    exampleVn: "... đang mặc chiếc váy trắng rất đẹp.",
  },
  {
    id: uuidv4(),
    sessionId: "unit6",
    en: "brief",
    vn: "ngắn gọn",
    exampleVn: "Câu trả lời của bạn nên thật ... và rõ ràng.",
  },
  {
    id: uuidv4(),
    sessionId: "unit6",
    en: "chase",
    vn: "đuổi theo",
    exampleVn: "Con chó đang ... con mèo khắp sân.",
  },
  {
    id: uuidv4(),
    sessionId: "unit6",
    en: "disappoint",
    vn: "làm thất vọng",
    exampleVn: "Tôi không muốn ... cha mẹ mình.",
  },
  {
    id: uuidv4(),
    sessionId: "unit6",
    en: "dive",
    vn: "lặn",
    exampleVn: "Anh ấy thích ... dưới biển để xem san hô.",
  },
  {
    id: uuidv4(),
    sessionId: "unit6",
    en: "exchange",
    vn: "trao đổi",
    exampleVn: "Chúng ta nên ... số điện thoại để liên lạc.",
  },
  {
    id: uuidv4(),
    sessionId: "unit6",
    en: "favor",
    vn: "ân huệ, giúp đỡ",
    exampleVn: "Bạn có thể làm cho tôi một ... không?",
  },
  {
    id: uuidv4(),
    sessionId: "unit6",
    en: "fee",
    vn: "học phí, lệ phí",
    exampleVn: "Tôi đã nộp ... cho khóa học mới.",
  },
  {
    id: uuidv4(),
    sessionId: "unit6",
    en: "forever",
    vn: "mãi mãi",
    exampleVn: "Tôi sẽ nhớ kỷ niệm đó ...",
  },
  {
    id: uuidv4(),
    sessionId: "unit6",
    en: "guy",
    vn: "chàng trai, người đàn ông",
    exampleVn: "... đó là bạn thân của tôi.",
  },
  {
    id: uuidv4(),
    sessionId: "unit6",
    en: "lovely",
    vn: "đáng yêu",
    exampleVn: "Cô bé thật ... với nụ cười tươi.",
  },
  {
    id: uuidv4(),
    sessionId: "unit6",
    en: "mood",
    vn: "tâm trạng",
    exampleVn: "Hôm nay tôi không có ... để làm việc.",
  },
  {
    id: uuidv4(),
    sessionId: "unit6",
    en: "palace",
    vn: "cung điện",
    exampleVn: "Nhà vua sống trong một ... lớn.",
  },
  {
    id: uuidv4(),
    sessionId: "unit6",
    en: "permit",
    vn: "cho phép, giấy phép",
    exampleVn: "Bạn cần có ... để vào khu vực này.",
  },
  {
    id: uuidv4(),
    sessionId: "unit6",
    en: "protest",
    vn: "phản đối",
    exampleVn: "Họ đang ... quyết định của chính phủ.",
  },
  {
    id: uuidv4(),
    sessionId: "unit6",
    en: "sculpture",
    vn: "điêu khắc, tượng",
    exampleVn: "Bảo tàng có rất nhiều ... cổ xưa.",
  },
  {
    id: uuidv4(),
    sessionId: "unit6",
    en: "tribe",
    vn: "bộ lạc",
    exampleVn: "... này sống sâu trong rừng Amazon.",
  },
  {
    id: uuidv4(),
    sessionId: "unit6",
    en: "youth",
    vn: "tuổi trẻ, thanh niên",
    exampleVn: "... là khoảng thời gian đẹp nhất của cuộc đời.",
  },
  {
    id: uuidv4(),
    sessionId: "unit7",
    en: "basis",
    vn: "nền tảng, cơ sở",
    exampleVn: "Sự tin tưởng là ... của mọi mối quan hệ.",
  },
  {
    id: uuidv4(),
    sessionId: "unit7",
    en: "biology",
    vn: "sinh học",
    exampleVn: "Cô ấy đang học ... tại trường đại học.",
  },
  {
    id: uuidv4(),
    sessionId: "unit7",
    en: "cage",
    vn: "lồng, chuồng",
    exampleVn: "Con chim đang hót trong ...",
  },
  {
    id: uuidv4(),
    sessionId: "unit7",
    en: "colleague",
    vn: "đồng nghiệp",
    exampleVn: "Tôi có nhiều ... rất thân thiện.",
  },
  {
    id: uuidv4(),
    sessionId: "unit7",
    en: "colony",
    vn: "thuộc địa, bầy đàn",
    exampleVn: "Việt Nam từng là một ... của Pháp.",
  },
  {
    id: uuidv4(),
    sessionId: "unit7",
    en: "debate",
    vn: "cuộc tranh luận",
    exampleVn: "Chúng tôi đã có một ... sôi nổi về chính trị.",
  },
  {
    id: uuidv4(),
    sessionId: "unit7",
    en: "depart",
    vn: "khởi hành, rời đi",
    exampleVn: "Chuyến tàu sẽ ... lúc 8 giờ sáng.",
  },
  {
    id: uuidv4(),
    sessionId: "unit7",
    en: "depress",
    vn: "làm chán nản, làm suy giảm",
    exampleVn: "Tin xấu đó thật sự ... tôi.",
  },
  {
    id: uuidv4(),
    sessionId: "unit7",
    en: "factual",
    vn: "dựa trên sự thật",
    exampleVn: "Báo cáo này hoàn toàn ...",
  },
  {
    id: uuidv4(),
    sessionId: "unit7",
    en: "fascinate",
    vn: "làm mê hoặc, cuốn hút",
    exampleVn: "Những câu chuyện cổ tích luôn ... trẻ em.",
  },
  {
    id: uuidv4(),
    sessionId: "unit7",
    en: "mission",
    vn: "nhiệm vụ, sứ mệnh",
    exampleVn: "Đây là ... quan trọng nhất của chúng ta.",
  },
  {
    id: uuidv4(),
    sessionId: "unit7",
    en: "nevertheless",
    vn: "tuy nhiên, dù vậy",
    exampleVn: "Cô ấy mệt mỏi, ... vẫn tiếp tục làm việc.",
  },
  {
    id: uuidv4(),
    sessionId: "unit7",
    en: "occupation",
    vn: "nghề nghiệp, sự chiếm đóng",
    exampleVn: "Bác sĩ là ... đáng tự hào.",
  },
  {
    id: uuidv4(),
    sessionId: "unit7",
    en: "overseas",
    vn: "nước ngoài, hải ngoại",
    exampleVn: "Anh trai tôi đang làm việc ...",
  },
  {
    id: uuidv4(),
    sessionId: "unit7",
    en: "persuade",
    vn: "thuyết phục",
    exampleVn: "Tôi cố gắng ... cô ấy đồng ý.",
  },
  {
    id: uuidv4(),
    sessionId: "unit7",
    en: "route",
    vn: "tuyến đường, lộ trình",
    exampleVn: "Đây là ... nhanh nhất đến trung tâm thành phố.",
  },
  {
    id: uuidv4(),
    sessionId: "unit7",
    en: "ruins",
    vn: "tàn tích, đống đổ nát",
    exampleVn: "Chúng tôi tham quan ... của một ngôi đền cổ.",
  },
  {
    id: uuidv4(),
    sessionId: "unit7",
    en: "scholar",
    vn: "học giả, nhà nghiên cứu",
    exampleVn: "Ông ấy là một ... nổi tiếng trong lĩnh vực lịch sử.",
  },
  {
    id: uuidv4(),
    sessionId: "unit7",
    en: "significant",
    vn: "quan trọng, đáng kể",
    exampleVn: "Đây là một bước tiến ... trong khoa học.",
  },
  {
    id: uuidv4(),
    sessionId: "unit7",
    en: "volcano",
    vn: "núi lửa",
    exampleVn: "... phun trào gây thiệt hại lớn cho khu vực.",
  },

  {
    id: uuidv4(),
    sessionId: "unit8",
    en: "broad",
    vn: "rộng, bao quát",
    exampleVn: "Con đường này rất ..., có thể đi được hai xe.",
  },
  {
    id: uuidv4(),
    sessionId: "unit8",
    en: "bush",
    vn: "bụi cây",
    exampleVn: "Có một con mèo đang trốn sau ....",
  },
  {
    id: uuidv4(),
    sessionId: "unit8",
    en: "capable",
    vn: "có khả năng",
    exampleVn: "Cô ấy ... giải quyết mọi vấn đề khó khăn.",
  },
  {
    id: uuidv4(),
    sessionId: "unit8",
    en: "cheat",
    vn: "gian lận",
    exampleVn: "Anh ta bị phát hiện ... trong kỳ thi.",
  },
  {
    id: uuidv4(),
    sessionId: "unit8",
    en: "concentrate",
    vn: "tập trung",
    exampleVn: "Hãy ... vào bài học, đừng phân tâm.",
  },
  {
    id: uuidv4(),
    sessionId: "unit8",
    en: "conclude",
    vn: "kết luận",
    exampleVn: "Giáo viên ... rằng bài làm của em rất tốt.",
  },
  {
    id: uuidv4(),
    sessionId: "unit8",
    en: "confident",
    vn: "tự tin",
    exampleVn: "Cô ấy rất .... khi nói trước đám đông.",
  },
  {
    id: uuidv4(),
    sessionId: "unit8",
    en: "considerable",
    vn: "đáng kể",
    exampleVn: "Dự án này tốn một khoản chi phí ....",
  },
  {
    id: uuidv4(),
    sessionId: "unit8",
    en: "convey",
    vn: "truyền đạt, chuyển tải",
    exampleVn: "Anh ấy không thể ... rõ ý của mình.",
  },
  {
    id: uuidv4(),
    sessionId: "unit8",
    en: "definite",
    vn: "chắc chắn, rõ ràng",
    exampleVn: "Chúng tôi chưa có kế hoạch ... cho kỳ nghỉ.",
  },
  {
    id: uuidv4(),
    sessionId: "unit8",
    en: "delight",
    vn: "niềm vui, thích thú",
    exampleVn: "Trẻ con reo lên ... khi thấy quà.",
  },
  {
    id: uuidv4(),
    sessionId: "unit8",
    en: "destination",
    vn: "điểm đến",
    exampleVn: "Paris là ... mơ ước của nhiều người.",
  },
  {
    id: uuidv4(),
    sessionId: "unit8",
    en: "dictate",
    vn: "ra lệnh, đọc cho viết",
    exampleVn: "Giáo viên ... cho học sinh chép bài.",
  },
  {
    id: uuidv4(),
    sessionId: "unit8",
    en: "edge",
    vn: "cạnh, bờ, mép",
    exampleVn: "Cẩn thận khi đứng gần ... bàn.",
  },
  {
    id: uuidv4(),
    sessionId: "unit8",
    en: "path",
    vn: "con đường, lối đi",
    exampleVn: "Họ đi dạo trên ... nhỏ trong rừng.",
  },
  {
    id: uuidv4(),
    sessionId: "unit8",
    en: "resort",
    vn: "khu nghỉ dưỡng; dùng đến",
    exampleVn: "Chúng tôi nghỉ ở một khu ... ven biển.",
  },
  {
    id: uuidv4(),
    sessionId: "unit8",
    en: "shadow",
    vn: "bóng, bóng tối",
    exampleVn: "... của anh ấy đổ dài trên mặt đất.",
  },
  {
    id: uuidv4(),
    sessionId: "unit8",
    en: "succeed",
    vn: "thành công",
    exampleVn: "Cô ấy đã ... sau nhiều năm cố gắng.",
  },
  {
    id: uuidv4(),
    sessionId: "unit8",
    en: "suspect",
    vn: "nghi ngờ; kẻ tình nghi",
    exampleVn: "Cảnh sát ... anh ta liên quan đến vụ án.",
  },
  {
    id: uuidv4(),
    sessionId: "unit8",
    en: "valley",
    vn: "thung lũng",
    exampleVn: "Ngôi làng nhỏ nằm giữa ... xanh.",
  },

  {
    id: uuidv4(),
    sessionId: "unit9",
    en: "admire",
    vn: "ngưỡng mộ",
    exampleVn: "Tôi rất ... lòng dũng cảm của anh ấy.",
  },
  {
    id: uuidv4(),
    sessionId: "unit9",
    en: "aid",
    vn: "viện trợ, giúp đỡ",
    exampleVn: "Họ gửi .... đến vùng bị thiên tai.",
  },
  {
    id: uuidv4(),
    sessionId: "unit9",
    en: "attempt",
    vn: "cố gắng, nỗ lực",
    exampleVn: "Anh ấy đang ... hoàn thành công việc đúng hạn.",
  },
  {
    id: uuidv4(),
    sessionId: "unit9",
    en: "authority",
    vn: "thẩm quyền, quyền lực",
    exampleVn: "... địa phương có thẩm quyền xử lý vụ việc.",
  },
  {
    id: uuidv4(),
    sessionId: "unit9",
    en: "capital",
    vn: "thủ đô, vốn",
    exampleVn: "Hà Nội là ... của Việt Nam.",
  },
  {
    id: uuidv4(),
    sessionId: "unit9",
    en: "cooperate",
    vn: "hợp tác",
    exampleVn: "Hai công ty ...để phát triển sản phẩm mới.",
  },
  {
    id: uuidv4(),
    sessionId: "unit9",
    en: "defend",
    vn: "bảo vệ, phòng thủ",
    exampleVn: "Anh ta cố gắng ... danh dự của mình.",
  },
  {
    id: uuidv4(),
    sessionId: "unit9",
    en: "destruction",
    vn: "sự phá hủy",
    exampleVn: "Trận động đất gây ra ... nghiêm trọng.",
  },
  {
    id: uuidv4(),
    sessionId: "unit9",
    en: "disorder",
    vn: "rối loạn, lộn xộn",
    exampleVn: "Căn phòng ... sau buổi tiệc.",
  },
  {
    id: uuidv4(),
    sessionId: "unit9",
    en: "division",
    vn: "sự phân chia",
    exampleVn: "Công việc được ... đều cho các nhóm.",
  },
  {
    id: uuidv4(),
    sessionId: "unit9",
    en: "enable",
    vn: "cho phép, làm cho có thể",
    exampleVn: "Ứng dụng này ... người dùng học tiếng Anh dễ dàng hơn.",
  },
  {
    id: uuidv4(),
    sessionId: "unit9",
    en: "frustrate",
    vn: "làm thất vọng, cản trở",
    exampleVn: "Kế hoạch bị ... bởi thời tiết xấu.",
  },
  {
    id: uuidv4(),
    sessionId: "unit9",
    en: "govern",
    vn: "cai trị, quản lý",
    exampleVn: "Nhà vua ... đất nước trong nhiều năm.",
  },
  {
    id: uuidv4(),
    sessionId: "unit9",
    en: "plenty",
    vn: "nhiều, dồi dào",
    exampleVn: "Chúng ta còn ... thời gian để chuẩn bị.",
  },
  {
    id: uuidv4(),
    sessionId: "unit9",
    en: "relieve",
    vn: "làm dịu đi, giảm nhẹ",
    exampleVn: "Thuốc giúp giảm ... cơn đau.",
  },
  {
    id: uuidv4(),
    sessionId: "unit9",
    en: "reputation",
    vn: "danh tiếng",
    exampleVn: "Công ty này có... rất tốt.",
  },
  {
    id: uuidv4(),
    sessionId: "unit9",
    en: "royal",
    vn: "hoàng gia",
    exampleVn: "Gia đình ... sống trong cung điện sang trọng.",
  },
  {
    id: uuidv4(),
    sessionId: "unit9",
    en: "slave",
    vn: "nô lệ",
    exampleVn: "Ngày xưa có rất nhiều người phải sống kiếp ....",
  },
  {
    id: uuidv4(),
    sessionId: "unit9",
    en: "struggle",
    vn: "đấu tranh, vật lộn",
    exampleVn: "Cô ấy phải ... để nuôi con một mình.",
  },
  {
    id: uuidv4(),
    sessionId: "unit9",
    en: "stupid",
    vn: "ngu ngốc",
    exampleVn: "Đừng làm những việc ... như thế nữa.",
  },

  {
    id: uuidv4(),
    sessionId: "unit10",
    en: "citizen",
    vn: "công dân",
    exampleVn: "... của nước Việt Nam.",
  },
  {
    id: uuidv4(),
    sessionId: "unit10",
    en: "council",
    vn: "hội đồng",
    exampleVn: "... đã họp để bàn về kế hoạch mới.",
  },
  {
    id: uuidv4(),
    sessionId: "unit10",
    en: "declare",
    vn: "tuyên bố, khai báo",
    exampleVn: "Chính phủ ... tình trạng khẩn cấp.",
  },
  {
    id: uuidv4(),
    sessionId: "unit10",
    en: "enormous",
    vn: "to lớn, khổng lồ",
    exampleVn: "Ngôi nhà này ... hơn tôi tưởng.",
  },
  {
    id: uuidv4(),
    sessionId: "unit10",
    en: "extraordinary",
    vn: "phi thường, đặc biệt",
    exampleVn: "Cô ấy có tài năng ... trong âm nhạc.",
  },
  {
    id: uuidv4(),
    sessionId: "unit10",
    en: "fog",
    vn: "sương mù",
    exampleVn: "Buổi sáng có ... dày đặc.",
  },
  {
    id: uuidv4(),
    sessionId: "unit10",
    en: "funeral",
    vn: "đám tang",
    exampleVn: "Anh ấy buồn vì vừa dự một ... của người thân.",
  },
  {
    id: uuidv4(),
    sessionId: "unit10",
    en: "giant",
    vn: "người khổng lồ",
    exampleVn: "Câu chuyện kể về một ... sống trong rừng.",
  },
  {
    id: uuidv4(),
    sessionId: "unit10",
    en: "impression",
    vn: "ấn tượng",
    exampleVn: "Tôi có ... tốt về cô ấy trong buổi gặp đầu tiên.",
  },
  {
    id: uuidv4(),
    sessionId: "unit10",
    en: "income",
    vn: "thu nhập",
    exampleVn: "... của anh ta tăng đáng kể sau khi đổi việc.",
  },
  {
    id: uuidv4(),
    sessionId: "unit10",
    en: "mad",
    vn: "điên, phát điên",
    exampleVn: "Cô ấy gần như ... vì bị phản bội.",
  },
  {
    id: uuidv4(),
    sessionId: "unit10",
    en: "ought",
    vn: "nên, phải",
    exampleVn: "Bạn ... học chăm hơn để đạt kết quả tốt.",
  },
  {
    id: uuidv4(),
    sessionId: "unit10",
    en: "resist",
    vn: "chống lại, kháng cự",
    exampleVn: "Anh ta cố ... lại cơn đau.",
  },
  {
    id: uuidv4(),
    sessionId: "unit10",
    en: "reveal",
    vn: "tiết lộ, bộc lộ",
    exampleVn: "Cô ấy không muốn ... bí mật của mình.",
  },
  {
    id: uuidv4(),
    sessionId: "unit10",
    en: "rid",
    vn: "loại bỏ",
    exampleVn: "Tôi muốn ... thói quen xấu đó.",
  },
  {
    id: uuidv4(),
    sessionId: "unit10",
    en: "sword",
    vn: "thanh kiếm",
    exampleVn: "Hiệp sĩ rút ... ra khỏi vỏ.",
  },
  {
    id: uuidv4(),
    sessionId: "unit10",
    en: "tale",
    vn: "câu chuyện, truyện kể",
    exampleVn: "Bà kể cho chúng tôi nghe một ... cổ tích.",
  },
  {
    id: uuidv4(),
    sessionId: "unit10",
    en: "trap",
    vn: "cái bẫy",
    exampleVn: "Họ đặt ... để bắt động vật.",
  },
  {
    id: uuidv4(),
    sessionId: "unit10",
    en: "trial",
    vn: "phiên tòa, thử nghiệm",
    exampleVn: "Tội phạm đang bị xét xử trong một ... lớn.",
  },
  {
    id: uuidv4(),
    sessionId: "unit10",
    en: "violent",
    vn: "bạo lực, dữ dội",
    exampleVn: "Bộ phim này quá ... đối với trẻ nhỏ.",
  },

  {
    id: uuidv4(),
    sessionId: "unit11",
    en: "admission",
    vn: "sự nhận vào, sự thú nhận",
    exampleVn: "Anh ta ... thú nhận tội.",
  },
  {
    id: uuidv4(),
    sessionId: "unit11",
    en: "astronomy",
    vn: "thiên văn học",
    exampleVn: "Cô ấy rất thích ... và thường ngắm sao mỗi tối.",
  },
  {
    id: uuidv4(),
    sessionId: "unit11",
    en: "blame",
    vn: "đổ lỗi, trách",
    exampleVn: "Đừng ... tôi cho sai lầm này.",
  },
  {
    id: uuidv4(),
    sessionId: "unit11",
    en: "chemistry",
    vn: "hóa học",
    exampleVn: "Tôi thích ... vì nó giúp hiểu cách vật chất hoạt động.",
  },
  {
    id: uuidv4(),
    sessionId: "unit11",
    en: "despite",
    vn: "mặc dù",
    exampleVn: "... trời mưa, họ vẫn tiếp tục chơi bóng.",
  },
  {
    id: uuidv4(),
    sessionId: "unit11",
    en: "dinosaur",
    vn: "khủng long",
    exampleVn: "Trẻ con thường thích xem phim về ... thời tiền sử.",
  },
  {
    id: uuidv4(),
    sessionId: "unit11",
    en: "exhibit",
    vn: "trưng bày, triển lãm",
    exampleVn: "Bảo tàng đang ... nhiều cổ vật quý hiếm.",
  },
  {
    id: uuidv4(),
    sessionId: "unit11",
    en: "fame",
    vn: "danh tiếng",
    exampleVn: "Anh ta đạt được ... sau khi ra mắt album đầu tiên.",
  },
  {
    id: uuidv4(),
    sessionId: "unit11",
    en: "forecast",
    vn: "dự báo",
    exampleVn: "Bản tin thời tiết ... ngày mai trời sẽ nắng.",
  },
  {
    id: uuidv4(),
    sessionId: "unit11",
    en: "genius",
    vn: "thiên tài",
    exampleVn: "Einstein được coi là một ... trong lĩnh vực vật lý.",
  },
  {
    id: uuidv4(),
    sessionId: "unit11",
    en: "gentle",
    vn: "dịu dàng, nhẹ nhàng",
    exampleVn: "Cô ấy nói chuyện rất ... và khiến ai cũng dễ chịu.",
  },
  {
    id: uuidv4(),
    sessionId: "unit11",
    en: "geography",
    vn: "địa lý",
    exampleVn: "Tôi đang học ... để hiểu rõ hơn về các quốc gia trên thế giới.",
  },
  {
    id: uuidv4(),
    sessionId: "unit11",
    en: "interfere",
    vn: "can thiệp, xen vào",
    exampleVn: "Đừng ... vào chuyện riêng của người khác.",
  },
  {
    id: uuidv4(),
    sessionId: "unit11",
    en: "lightly",
    vn: "nhẹ nhàng",
    exampleVn: "Cô ấy đặt tay ... lên vai tôi.",
  },
  {
    id: uuidv4(),
    sessionId: "unit11",
    en: "principal",
    vn: "hiệu trưởng, chính yếu",
    exampleVn: "... của trường đã phát biểu trong lễ khai giảng.",
  },
  {
    id: uuidv4(),
    sessionId: "unit11",
    en: "row",
    vn: "hàng, dãy; cãi nhau",
    exampleVn: "Chúng tôi ngồi ở ... đầu trong rạp chiếu phim.",
  },
  {
    id: uuidv4(),
    sessionId: "unit11",
    en: "shelf",
    vn: "kệ, giá",
    exampleVn: "Những cuốn sách được xếp gọn gàng trên ... trong phòng khách.",
  },
  {
    id: uuidv4(),
    sessionId: "unit11",
    en: "spite",
    vn: "sự thù hằn",
    exampleVn: "Cô ấy vẫn giúp anh ta ... những gì đã xảy ra.",
  },
  {
    id: uuidv4(),
    sessionId: "unit11",
    en: "super",
    vn: "tuyệt vời, siêu",
    exampleVn: "Bộ phim này thật ...! Tôi muốn xem lại lần nữa.",
  },
  {
    id: uuidv4(),
    sessionId: "unit11",
    en: "wet",
    vn: "ướt",
    exampleVn: "Áo của tôi bị ... sau cơn mưa lớn.",
  },

  {
    id: uuidv4(),
    sessionId: "unit12",
    en: "abuse",
    vn: "lạm dụng, ngược đãi",
    exampleVn: "Anh ta bị bắt vì ... quyền lực của mình.",
  },
  {
    id: uuidv4(),
    sessionId: "unit12",
    en: "afford",
    vn: "có khả năng chi trả",
    exampleVn: "Anh ta có ... cho bữa tối.",
  },
  {
    id: uuidv4(),
    sessionId: "unit12",
    en: "bake",
    vn: "nướng (bánh, đồ ăn)",
    exampleVn: "Mẹ tôi thích ... bánh quy vào cuối tuần.",
  },
  {
    id: uuidv4(),
    sessionId: "unit12",
    en: "bean",
    vn: "hạt đậu",
    exampleVn: "Chúng tôi trồng nhiều ... trong vườn sau nhà.",
  },
  {
    id: uuidv4(),
    sessionId: "unit12",
    en: "candle",
    vn: "cây nến",
    exampleVn: "Cô ấy thắp một ... trong buổi tối sinh nhật.",
  },
  {
    id: uuidv4(),
    sessionId: "unit12",
    en: "convert",
    vn: "chuyển đổi",
    exampleVn: "Anh ta ... căn gác mái thành phòng làm việc.",
  },
  {
    id: uuidv4(),
    sessionId: "unit12",
    en: "debt",
    vn: "nợ nần",
    exampleVn: "Cô ấy đang cố gắng trả hết ... sau khi vay ngân hàng.",
  },
  {
    id: uuidv4(),
    sessionId: "unit12",
    en: "decrease",
    vn: "giảm, suy giảm",
    exampleVn: "Giá xăng đã ... đáng kể trong tháng này.",
  },
  {
    id: uuidv4(),
    sessionId: "unit12",
    en: "fault",
    vn: "lỗi, sai sót",
    exampleVn: "Đó không phải ... của tôi, tôi đã làm đúng rồi.",
  },
  {
    id: uuidv4(),
    sessionId: "unit12",
    en: "fund",
    vn: "quỹ, cấp vốn",
    exampleVn: "Chính phủ sẽ ... cho dự án giáo dục mới.",
  },
  {
    id: uuidv4(),
    sessionId: "unit12",
    en: "generous",
    vn: "hào phóng",
    exampleVn: "Cô ấy rất ... khi quyên góp tiền cho trẻ em nghèo.",
  },
  {
    id: uuidv4(),
    sessionId: "unit12",
    en: "ingredient",
    vn: "thành phần, nguyên liệu",
    exampleVn: "Bột và trứng là những ... chính để làm bánh.",
  },
  {
    id: uuidv4(),
    sessionId: "unit12",
    en: "insist",
    vn: "khăng khăng, nhấn mạnh",
    exampleVn: "Anh ấy ... rằng mình không hề sai.",
  },
  {
    id: uuidv4(),
    sessionId: "unit12",
    en: "mess",
    vn: "mớ hỗn độn, lộn xộn",
    exampleVn: "Phòng của cậu ấy thật là một ... sau bữa tiệc.",
  },
  {
    id: uuidv4(),
    sessionId: "unit12",
    en: "metal",
    vn: "kim loại",
    exampleVn: "Cánh cửa này được làm bằng ... rất chắc chắn.",
  },
  {
    id: uuidv4(),
    sessionId: "unit12",
    en: "monitor",
    vn: "giám sát, màn hình",
    exampleVn: "Giáo viên ... học sinh trong suốt kỳ thi.",
  },
  {
    id: uuidv4(),
    sessionId: "unit12",
    en: "oppose",
    vn: "phản đối",
    exampleVn: "Nhiều người ... việc tăng thuế.",
  },
  {
    id: uuidv4(),
    sessionId: "unit12",
    en: "passive",
    vn: "bị động",
    exampleVn: "Cậu ấy luôn giữ thái độ ... trong mọi cuộc tranh luận.",
  },
  {
    id: uuidv4(),
    sessionId: "unit12",
    en: "quantity",
    vn: "số lượng",
    exampleVn: "Chúng tôi cần kiểm tra ... hàng tồn kho.",
  },
  {
    id: uuidv4(),
    sessionId: "unit12",
    en: "sue",
    vn: "kiện, khởi kiện",
    exampleVn: "Công ty quyết định ... đối tác vì vi phạm hợp đồng.",
  },

  {
    id: uuidv4(),
    sessionId: "unit13",
    en: "anxiety",
    vn: "sự lo lắng, lo âu",
    exampleVn: "Cô ấy cảm thấy ... trước buổi phỏng vấn.",
  },
  {
    id: uuidv4(),
    sessionId: "unit13",
    en: "army",
    vn: "quân đội",
    exampleVn: "Anh trai tôi đang phục vụ trong ... quốc gia.",
  },
  {
    id: uuidv4(),
    sessionId: "unit13",
    en: "billion",
    vn: "tỷ",
    exampleVn: "Công ty này có doanh thu hơn một ... đô la mỗi năm.",
  },
  {
    id: uuidv4(),
    sessionId: "unit13",
    en: "carve",
    vn: "chạm khắc, cắt tạc",
    exampleVn: "Ông ấy ... bức tượng từ gỗ sồi.",
  },
  {
    id: uuidv4(),
    sessionId: "unit13",
    en: "consult",
    vn: "tham khảo, hỏi ý kiến",
    exampleVn: "Tôi cần ... bác sĩ trước khi uống thuốc này.",
  },
  {
    id: uuidv4(),
    sessionId: "unit13",
    en: "emergency",
    vn: "tình huống khẩn cấp",
    exampleVn: "Trong trường hợp ..., hãy gọi 115 ngay lập tức.",
  },
  {
    id: uuidv4(),
    sessionId: "unit13",
    en: "fortune",
    vn: "vận may, tài sản lớn",
    exampleVn: "Anh ta kiếm được một ... nhờ đầu tư sớm vào công nghệ.",
  },
  {
    id: uuidv4(),
    sessionId: "unit13",
    en: "guarantee",
    vn: "đảm bảo, cam kết",
    exampleVn: "Chúng tôi ... sản phẩm được hoàn tiền nếu có lỗi.",
  },
  {
    id: uuidv4(),
    sessionId: "unit13",
    en: "hike",
    vn: "đi bộ đường dài, leo núi",
    exampleVn: "Cuối tuần này, nhóm tôi sẽ ... ở Đà Lạt.",
  },
  {
    id: uuidv4(),
    sessionId: "unit13",
    en: "initial",
    vn: "ban đầu",
    exampleVn: "Kế hoạch ... của họ đã thay đổi sau cuộc họp.",
  },
  {
    id: uuidv4(),
    sessionId: "unit13",
    en: "intense",
    vn: "mãnh liệt, dữ dội",
    exampleVn: "Trận đấu diễn ra vô cùng ... giữa hai đội.",
  },
  {
    id: uuidv4(),
    sessionId: "unit13",
    en: "lend",
    vn: "cho mượn, cho vay",
    exampleVn: "Anh có thể ... tôi ít tiền được không?",
  },
  {
    id: uuidv4(),
    sessionId: "unit13",
    en: "peak",
    vn: "đỉnh, cao điểm",
    exampleVn: "Chúng tôi đến đỉnh núi vào lúc ... của mùa đông.",
  },
  {
    id: uuidv4(),
    sessionId: "unit13",
    en: "potential",
    vn: "tiềm năng",
    exampleVn: "Cậu ấy có ... trở thành một nhà lãnh đạo giỏi.",
  },
  {
    id: uuidv4(),
    sessionId: "unit13",
    en: "pride",
    vn: "niềm tự hào",
    exampleVn: "Cô ấy luôn thể hiện ... về gia đình mình.",
  },
  {
    id: uuidv4(),
    sessionId: "unit13",
    en: "proof",
    vn: "bằng chứng",
    exampleVn: "Cảnh sát yêu cầu ... về lời khai của nhân chứng.",
  },
  {
    id: uuidv4(),
    sessionId: "unit13",
    en: "quit",
    vn: "bỏ, nghỉ",
    exampleVn: "Anh ta quyết định ... công việc để theo đuổi ước mơ.",
  },
  {
    id: uuidv4(),
    sessionId: "unit13",
    en: "spin",
    vn: "xoay tròn",
    exampleVn: "Chiếc đĩa bắt đầu ... khi bật máy lên.",
  },
  {
    id: uuidv4(),
    sessionId: "unit13",
    en: "tiny",
    vn: "nhỏ bé",
    exampleVn: "Con mèo con thật ... và dễ thương.",
  },
  {
    id: uuidv4(),
    sessionId: "unit13",
    en: "tutor",
    vn: "gia sư, người dạy kèm",
    exampleVn: "Tôi thuê một ... để giúp con học toán.",
  },

  {
    id: uuidv4(),
    sessionId: "unit14",
    en: "apparent",
    vn: "rõ ràng, hiển nhiên",
    exampleVn: "... là anh ta đang nói dối.",
  },
  {
    id: uuidv4(),
    sessionId: "unit14",
    en: "blind",
    vn: "mù, không nhìn thấy",
    exampleVn: "Anh ấy bị ... từ khi sinh ra.",
  },
  {
    id: uuidv4(),
    sessionId: "unit14",
    en: "calculate",
    vn: "tính toán",
    exampleVn: "Tôi đang ... chi phí cho chuyến đi.",
  },
  {
    id: uuidv4(),
    sessionId: "unit14",
    en: "chat",
    vn: "tán gẫu, nói chuyện phiếm",
    exampleVn: "Chúng tôi ngồi ... ở quán cà phê.",
  },
  {
    id: uuidv4(),
    sessionId: "unit14",
    en: "commit",
    vn: "cam kết, phạm (tội)",
    exampleVn: "Anh ta đã ... một sai lầm lớn.",
  },
  {
    id: uuidv4(),
    sessionId: "unit14",
    en: "compose",
    vn: "sáng tác, soạn",
    exampleVn: "Cô ấy đang ... một bản nhạc mới.",
  },
  {
    id: uuidv4(),
    sessionId: "unit14",
    en: "dormitory",
    vn: "ký túc xá",
    exampleVn: "Tôi ở trong ... của trường.",
  },
  {
    id: uuidv4(),
    sessionId: "unit14",
    en: "exhaust",
    vn: "làm kiệt sức",
    exampleVn: "Buổi làm việc hôm nay khiến tôi ....",
  },
  {
    id: uuidv4(),
    sessionId: "unit14",
    en: "greenhouse",
    vn: "nhà kính",
    exampleVn: "Họ trồng hoa trong ... suốt năm.",
  },
  {
    id: uuidv4(),
    sessionId: "unit14",
    en: "ignore",
    vn: "phớt lờ, bỏ qua",
    exampleVn: "Anh ta cố tình ... lời khuyên của tôi.",
  },
  {
    id: uuidv4(),
    sessionId: "unit14",
    en: "obvious",
    vn: "rõ ràng, hiển nhiên",
    exampleVn: "Điều đó ... với mọi người.",
  },
  {
    id: uuidv4(),
    sessionId: "unit14",
    en: "physics",
    vn: "vật lý học",
    exampleVn: "Tôi học ... ở trường đại học.",
  },
  {
    id: uuidv4(),
    sessionId: "unit14",
    en: "portion",
    vn: "phần, khẩu phần",
    exampleVn: "Anh ta chỉ ăn một ... nhỏ của chiếc bánh.",
  },
  {
    id: uuidv4(),
    sessionId: "unit14",
    en: "remind",
    vn: "nhắc nhở",
    exampleVn: "... tôi nộp bài vào ngày mai nhé.",
  },
  {
    id: uuidv4(),
    sessionId: "unit14",
    en: "secretary",
    vn: "thư ký",
    exampleVn: "... của tôi sẽ gửi email cho anh.",
  },
  {
    id: uuidv4(),
    sessionId: "unit14",
    en: "severe",
    vn: "nghiêm trọng, khắc nghiệt",
    exampleVn: "Cơn bão này rất ....",
  },
  {
    id: uuidv4(),
    sessionId: "unit14",
    en: "talent",
    vn: "tài năng",
    exampleVn: "Cô bé có ... âm nhạc thiên bẩm.",
  },
  {
    id: uuidv4(),
    sessionId: "unit14",
    en: "thesis",
    vn: "luận văn, luận án",
    exampleVn: "Tôi đang viết ... tốt nghiệp.",
  },
  {
    id: uuidv4(),
    sessionId: "unit14",
    en: "uniform",
    vn: "đồng phục",
    exampleVn: "Học sinh phải mặc ... mỗi ngày.",
  },
  {
    id: uuidv4(),
    sessionId: "unit14",
    en: "vision",
    vn: "tầm nhìn, thị giác",
    exampleVn: "Anh ta có ... xa trong kinh doanh.",
  },

  {
    id: uuidv4(),
    sessionId: "unit15",
    en: "absorb",
    vn: "hấp thụ",
    exampleVn: "Cây ... nước từ đất.",
  },
  {
    id: uuidv4(),
    sessionId: "unit15",
    en: "boss",
    vn: "ông chủ, sếp",
    exampleVn: "... tôi rất nghiêm khắc.",
  },
  {
    id: uuidv4(),
    sessionId: "unit15",
    en: "committee",
    vn: "ủy ban",
    exampleVn: "... đã thông qua kế hoạch mới.",
  },
  {
    id: uuidv4(),
    sessionId: "unit15",
    en: "contract",
    vn: "hợp đồng",
    exampleVn: "Chúng tôi đã ký ... hôm qua.",
  },
  {
    id: uuidv4(),
    sessionId: "unit15",
    en: "crew",
    vn: "thủy thủ đoàn, đội",
    exampleVn: "... quay phim đang chuẩn bị cảnh tiếp theo.",
  },
  {
    id: uuidv4(),
    sessionId: "unit15",
    en: "devote",
    vn: "cống hiến, dành cho",
    exampleVn: "Cô ấy ... cả đời cho nghệ thuật.",
  },
  {
    id: uuidv4(),
    sessionId: "unit15",
    en: "dig",
    vn: "đào",
    exampleVn: "Họ đang ... hố để trồng cây.",
  },
  {
    id: uuidv4(),
    sessionId: "unit15",
    en: "dine",
    vn: "ăn tối",
    exampleVn: "Chúng tôi ... tại một nhà hàng sang trọng.",
  },
  {
    id: uuidv4(),
    sessionId: "unit15",
    en: "donate",
    vn: "quyên góp",
    exampleVn: "Anh ấy thường xuyên ... cho tổ chức từ thiện.",
  },
  {
    id: uuidv4(),
    sessionId: "unit15",
    en: "double",
    vn: "gấp đôi",
    exampleVn: "Doanh thu tháng này tăng ... so với tháng trước.",
  },
  {
    id: uuidv4(),
    sessionId: "unit15",
    en: "elevate",
    vn: "nâng lên, nâng cao",
    exampleVn: "Chúng tôi muốn .... chất lượng dịch vụ.",
  },
  {
    id: uuidv4(),
    sessionId: "unit15",
    en: "flavor",
    vn: "hương vị",
    exampleVn: "Tôi thích .... vani của kem này.",
  },
  {
    id: uuidv4(),
    sessionId: "unit15",
    en: "foundation",
    vn: "nền tảng, cơ sở",
    exampleVn: "Giáo dục là ... của sự thành công.",
  },
  {
    id: uuidv4(),
    sessionId: "unit15",
    en: "generation",
    vn: "thế hệ",
    exampleVn: "... trẻ ngày nay năng động hơn nhiều.",
  },
  {
    id: uuidv4(),
    sessionId: "unit15",
    en: "handle",
    vn: "xử lý, tay cầm",
    exampleVn: "Tôi sẽ ... vấn đề này ngay lập tức.",
  },
  {
    id: uuidv4(),
    sessionId: "unit15",
    en: "layer",
    vn: "lớp, tầng",
    exampleVn: "Chiếc bánh có ba ... kem.",
  },
  {
    id: uuidv4(),
    sessionId: "unit15",
    en: "mud",
    vn: "bùn",
    exampleVn: "Giày tôi bị dính đầy ... sau cơn mưa.",
  },
  {
    id: uuidv4(),
    sessionId: "unit15",
    en: "smooth",
    vn: "mịn, trơn tru",
    exampleVn: "Da em bé rất .... màng.",
  },
  {
    id: uuidv4(),
    sessionId: "unit15",
    en: "soil",
    vn: "đất",
    exampleVn: "Người nông dân đang cày xới .... để trồng trọt.",
  },
  {
    id: uuidv4(),
    sessionId: "unit15",
    en: "unique",
    vn: "độc đáo, duy nhất",
    exampleVn: "Thiết kế này rất .... và sáng tạo.",
  },
];
