import { ISessionItem, IStoryItem, IUnitItem } from "@/interfaces/common";
import { v4 as uuidv4 } from "uuid";

export const initialEssentialUnit: IUnitItem[] = [
  {
    id: "book2",
    title: "4000 Essential English Word 2",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "book3",
    title: "4000 Essential English Word 3",
    subtitle: "4000 Essential English Word 3",
  },
  {
    id: "book4",
    title: "4000 Essential English Word 4",
    subtitle: "4000 Essential English Word 4",
  },
  {
    id: "book5",
    title: "4000 Essential English Word 5",
    subtitle: "4000 Essential English Word 5",
  },
  {
    id: "book6",
    title: "4000 Essential English Word 6",
    subtitle: "4000 Essential English Word 6",
  },
];
export const initialEssentialSession: ISessionItem[] = [
  {
    id: "unit2",
    unitId: "book2",
    title: "Unit 2",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit3",
    unitId: "book2",
    title: "Unit 3",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit4",
    unitId: "book2",
    title: "Unit 4",
    subtitle: "4000 Essential English Word 2",
  },

  {
    id: "unit5",
    unitId: "book2",
    title: "Unit 5",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit6",
    unitId: "book2",
    title: "Unit 6",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit7",
    unitId: "book2",
    title: "Unit 7",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit8",
    unitId: "book2",
    title: "Unit 8",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit9",
    unitId: "book2",
    title: "Unit 9",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit10",
    unitId: "book2",
    title: "Unit 10",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit11",
    unitId: "book2",
    title: "Unit 11",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit12",
    unitId: "book2",
    title: "Unit 12",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit13",
    unitId: "book2",
    title: "Unit 14",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit14",
    unitId: "book2",
    title: "Unit 14",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit15",
    unitId: "book2",
    title: "Unit 15",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit16",
    unitId: "book2",
    title: "Unit 16",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit17",
    unitId: "book2",
    title: "Unit 17",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit18",
    unitId: "book2",
    title: "Unit 18",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit19",
    unitId: "book2",
    title: "Unit 19",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit20",
    unitId: "book2",
    title: "Unit 20",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit21",
    unitId: "book2",
    title: "Unit 21",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit22",
    unitId: "book2",
    title: "Unit 22",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit23",
    unitId: "book2",
    title: "Unit 23",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit24",
    unitId: "book2",
    title: "Unit 24",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit25",
    unitId: "book2",
    title: "Unit 25",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit26",
    unitId: "book2",
    title: "Unit 26",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit27",
    unitId: "book2",
    title: "Unit 27",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit28",
    unitId: "book2",
    title: "Unit 28",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit29",
    unitId: "book2",
    title: "Unit 29",
    subtitle: "4000 Essential English Word 2",
  },
  {
    id: "unit30",
    unitId: "book2",
    title: "Unit 30",
    subtitle: "4000 Essential English Word 2",
  },
];
export const initialEssentialStoryEn: IStoryItem[] = [
  {
    id: uuidv4(),
    sessionId: "unit2",
    en: "bring",
    vn: "mang",
  },
  {
    id: uuidv4(),
    sessionId: "unit2",
    en: "castle",
    vn: "lâu đài",
  },
  {
    id: uuidv4(),
    sessionId: "unit2",
    en: "command",
    vn: "ra lệnh",
  },
  {
    id: uuidv4(),
    sessionId: "unit2",
    en: "counsel",
    vn: "tư vấn, khuyên nhủ",
  },
  {
    id: uuidv4(),
    sessionId: "unit2",
    en: "ensure",
    vn: "đảm bảo",
  },
  {
    id: uuidv4(),
    sessionId: "unit2",
    en: "explosion",
    vn: "vụ nổ",
  },
  {
    id: uuidv4(),
    sessionId: "unit2",
    en: "jewelry",
    vn: "trang sức",
  },
  {
    id: uuidv4(),
    sessionId: "unit2",
    en: "land",
    vn: "hạ cánh, đất đai",
  },
  {
    id: uuidv4(),
    sessionId: "unit2",
    en: "meteor",
    vn: "thiên thạch",
  },
  {
    id: uuidv4(),
    sessionId: "unit2",
    en: "monster",
    vn: "quái vật",
  },
  {
    id: uuidv4(),
    sessionId: "unit2",
    en: "northern",
    vn: "thuộc phía bắc",
  },
  {
    id: uuidv4(),
    sessionId: "unit2",
    en: "remote",
    vn: "xa xôi, hẻo lánh",
  },
  {
    id: uuidv4(),
    sessionId: "unit2",
    en: "southern",
    vn: "thuộc phía nam",
  },
  {
    id: uuidv4(),
    sessionId: "unit2",
    en: "statue",
    vn: "tượng",
  },
  {
    id: uuidv4(),
    sessionId: "unit2",
    en: "steam",
    vn: "hơi nước",
  },
  {
    id: uuidv4(),
    sessionId: "unit2",
    en: "submit",
    vn: "nộp, trình",
  },
  {
    id: uuidv4(),
    sessionId: "unit2",
    en: "temple",
    vn: "ngôi đền",
  },
  {
    id: uuidv4(),
    sessionId: "unit2",
    en: "upper",
    vn: "phía trên, cao hơn",
  },
  {
    id: uuidv4(),
    sessionId: "unit2",
    en: "weed",
    vn: "cỏ dại",
  },
  {
    id: uuidv4(),
    sessionId: "unit2",
    en: "wing",
    vn: "cánh",
  },
  {
    id: uuidv4(),
    sessionId: "unit3",
    en: "arrow",
    vn: "mũi tên",
  },
  {
    id: uuidv4(),
    sessionId: "unit3",
    en: "battle",
    vn: "trận chiến",
  },
  {
    id: uuidv4(),
    sessionId: "unit3",
    en: "bow",
    vn: "cái cung",
  },
  {
    id: uuidv4(),
    sessionId: "unit3",
    en: "brave",
    vn: "dũng cảm",
  },
  {
    id: uuidv4(),
    sessionId: "unit3",
    en: "chief",
    vn: "thủ lĩnh",
  },
  {
    id: uuidv4(),
    sessionId: "unit3",
    en: "disadvantage",
    vn: "bất lợi",
  },
  {
    id: uuidv4(),
    sessionId: "unit3",
    en: "enemy",
    vn: "kẻ thù",
  },
  {
    id: uuidv4(),
    sessionId: "unit3",
    en: "entrance",
    vn: "lối vào",
  },
  {
    id: uuidv4(),
    sessionId: "unit3",
    en: "hardly",
    vn: "hầu như không",
  },
  {
    id: uuidv4(),
    sessionId: "unit3",
    en: "intend",
    vn: "dự định",
  },
  {
    id: uuidv4(),
    sessionId: "unit3",
    en: "laughter",
    vn: "tiếng cười",
  },
  {
    id: uuidv4(),
    sessionId: "unit3",
    en: "log",
    vn: "khúc gỗ",
  },
  {
    id: uuidv4(),
    sessionId: "unit3",
    en: "military",
    vn: "quân đội",
  },
  {
    id: uuidv4(),
    sessionId: "unit3",
    en: "obey",
    vn: "vâng lời",
  },
  {
    id: uuidv4(),
    sessionId: "unit3",
    en: "secure",
    vn: "an toàn",
  },
  {
    id: uuidv4(),
    sessionId: "unit3",
    en: "steady",
    vn: "vững chắc",
  },
  {
    id: uuidv4(),
    sessionId: "unit3",
    en: "trust",
    vn: "tin tưởng",
  },
  {
    id: uuidv4(),
    sessionId: "unit3",
    en: "twist",
    vn: "xoắn, vặn",
  },
  {
    id: uuidv4(),
    sessionId: "unit3",
    en: "unless",
    vn: "trừ khi",
  },
  {
    id: uuidv4(),
    sessionId: "unit3",
    en: "weapon",
    vn: "vũ khí",
  },
  {
    id: uuidv4(),
    sessionId: "unit4",
    en: "chest",
    vn: "ngực",
  },
  {
    id: uuidv4(),
    sessionId: "unit4",
    en: "confidence",
    vn: "sự tự tin",
  },
  {
    id: uuidv4(),
    sessionId: "unit4",
    en: "consequence",
    vn: "hậu quả",
  },
  {
    id: uuidv4(),
    sessionId: "unit4",
    en: "disaster",
    vn: "thảm họa",
  },
  {
    id: uuidv4(),
    sessionId: "unit4",
    en: "disturb",
    vn: "làm phiền",
  },
  {
    id: uuidv4(),
    sessionId: "unit4",
    en: "estimate",
    vn: "ước lượng",
  },
  {
    id: uuidv4(),
    sessionId: "unit4",
    en: "honor",
    vn: "vinh dự, danh dự",
  },
  {
    id: uuidv4(),
    sessionId: "unit4",
    en: "impress",
    vn: "gây ấn tượng",
  },
  {
    id: uuidv4(),
    sessionId: "unit4",
    en: "marathon",
    vn: "cuộc chạy marathon",
  },
  {
    id: uuidv4(),
    sessionId: "unit4",
    en: "narrow",
    vn: "hẹp",
  },
  {
    id: uuidv4(),
    sessionId: "unit4",
    en: "pale",
    vn: "tái nhợt",
  },
  {
    id: uuidv4(),
    sessionId: "unit4",
    en: "rough",
    vn: "gồ ghề, thô ráp",
  },
  {
    id: uuidv4(),
    sessionId: "unit4",
    en: "satisfy",
    vn: "làm hài lòng",
  },
  {
    id: uuidv4(),
    sessionId: "unit4",
    en: "scream",
    vn: "thét, hét",
  },
  {
    id: uuidv4(),
    sessionId: "unit4",
    en: "sensitive",
    vn: "nhạy cảm",
  },
  {
    id: uuidv4(),
    sessionId: "unit4",
    en: "shade",
    vn: "bóng râm",
  },
  {
    id: uuidv4(),
    sessionId: "unit4",
    en: "supplement",
    vn: "bổ sung",
  },
  {
    id: uuidv4(),
    sessionId: "unit4",
    en: "terror",
    vn: "nỗi kinh hoàng",
  },
  {
    id: uuidv4(),
    sessionId: "unit4",
    en: "threat",
    vn: "mối đe dọa",
  },
  {
    id: uuidv4(),
    sessionId: "unit4",
    en: "victim",
    vn: "nạn nhân",
  },
  {
    id: uuidv4(),
    sessionId: "unit5",
    en: "ancestor",
    vn: "tổ tiên",
  },
  {
    id: uuidv4(),
    sessionId: "unit5",
    en: "angle",
    vn: "góc",
  },
  {
    id: uuidv4(),
    sessionId: "unit5",
    en: "boot",
    vn: "ủng",
  },
  {
    id: uuidv4(),
    sessionId: "unit5",
    en: "border",
    vn: "biên giới",
  },
  {
    id: uuidv4(),
    sessionId: "unit5",
    en: "congratulate",
    vn: "chúc mừng",
  },
  {
    id: uuidv4(),
    sessionId: "unit5",
    en: "frame",
    vn: "khung",
  },
  {
    id: uuidv4(),
    sessionId: "unit5",
    en: "heaven",
    vn: "thiên đường",
  },
  {
    id: uuidv4(),
    sessionId: "unit5",
    en: "incredible",
    vn: "khó tin, tuyệt vời",
  },
  {
    id: uuidv4(),
    sessionId: "unit5",
    en: "legend",
    vn: "huyền thoại",
  },
  {
    id: uuidv4(),
    sessionId: "unit5",
    en: "praise",
    vn: "khen ngợi",
  },
  {
    id: uuidv4(),
    sessionId: "unit5",
    en: "proceed",
    vn: "tiếp tục",
  },
  {
    id: uuidv4(),
    sessionId: "unit5",
    en: "pure",
    vn: "nguyên chất, tinh khiết",
  },
  {
    id: uuidv4(),
    sessionId: "unit5",
    en: "relative",
    vn: "họ hàng, người thân",
  },
  {
    id: uuidv4(),
    sessionId: "unit5",
    en: "senior",
    vn: "cao cấp, lớn tuổi",
  },
  {
    id: uuidv4(),
    sessionId: "unit5",
    en: "silent",
    vn: "im lặng",
  },
  {
    id: uuidv4(),
    sessionId: "unit5",
    en: "sink",
    vn: "chìm, bồn rửa",
  },
  {
    id: uuidv4(),
    sessionId: "unit5",
    en: "superior",
    vn: "vượt trội, cấp trên",
  },
  {
    id: uuidv4(),
    sessionId: "unit5",
    en: "surround",
    vn: "bao quanh",
  },
  {
    id: uuidv4(),
    sessionId: "unit5",
    en: "thick",
    vn: "dày",
  },
  {
    id: uuidv4(),
    sessionId: "unit5",
    en: "wrap",
    vn: "gói, bọc",
  },
  {
    id: uuidv4(),
    sessionId: "unit6",
    en: "abroad",
    vn: "ở nước ngoài",
  },
  {
    id: uuidv4(),
    sessionId: "unit6",
    en: "anger",
    vn: "sự tức giận",
  },
  {
    id: uuidv4(),
    sessionId: "unit6",
    en: "bride",
    vn: "cô dâu",
  },
  {
    id: uuidv4(),
    sessionId: "unit6",
    en: "brief",
    vn: "ngắn gọn",
  },
  {
    id: uuidv4(),
    sessionId: "unit6",
    en: "chase",
    vn: "đuổi theo",
  },
  {
    id: uuidv4(),
    sessionId: "unit6",
    en: "disappoint",
    vn: "làm thất vọng",
  },
  {
    id: uuidv4(),
    sessionId: "unit6",
    en: "dive",
    vn: "lặn",
  },
  {
    id: uuidv4(),
    sessionId: "unit6",
    en: "exchange",
    vn: "trao đổi",
  },
  {
    id: uuidv4(),
    sessionId: "unit6",
    en: "favor",
    vn: "ân huệ, giúp đỡ",
  },
  {
    id: uuidv4(),
    sessionId: "unit6",
    en: "fee",
    vn: "học phí, lệ phí",
  },
  {
    id: uuidv4(),
    sessionId: "unit6",
    en: "forever",
    vn: "mãi mãi",
  },
  {
    id: uuidv4(),
    sessionId: "unit6",
    en: "guy",
    vn: "chàng trai, người đàn ông",
  },
  {
    id: uuidv4(),
    sessionId: "unit6",
    en: "lovely",
    vn: "đáng yêu",
  },
  {
    id: uuidv4(),
    sessionId: "unit6",
    en: "mood",
    vn: "tâm trạng",
  },
  {
    id: uuidv4(),
    sessionId: "unit6",
    en: "palace",
    vn: "cung điện",
  },
  {
    id: uuidv4(),
    sessionId: "unit6",
    en: "permit",
    vn: "cho phép, giấy phép",
  },
  {
    id: uuidv4(),
    sessionId: "unit6",
    en: "protest",
    vn: "phản đối",
  },
  {
    id: uuidv4(),
    sessionId: "unit6",
    en: "sculpture",
    vn: "điêu khắc, tượng",
  },
  {
    id: uuidv4(),
    sessionId: "unit6",
    en: "tribe",
    vn: "bộ lạc",
  },
  {
    id: uuidv4(),
    sessionId: "unit6",
    en: "youth",
    vn: "tuổi trẻ, thanh niên",
  },
  {
    id: uuidv4(),
    sessionId: "unit7",
    en: "basis",
    vn: "nền tảng, cơ sở",
  },
  {
    id: uuidv4(),
    sessionId: "unit7",
    en: "biology",
    vn: "sinh học",
  },
  {
    id: uuidv4(),
    sessionId: "unit7",
    en: "cage",
    vn: "lồng, chuồng",
  },
  {
    id: uuidv4(),
    sessionId: "unit7",
    en: "colleague",
    vn: "đồng nghiệp",
  },
  {
    id: uuidv4(),
    sessionId: "unit7",
    en: "colony",
    vn: "thuộc địa, bầy đàn",
  },
  {
    id: uuidv4(),
    sessionId: "unit7",
    en: "debate",
    vn: "cuộc tranh luận",
  },
  {
    id: uuidv4(),
    sessionId: "unit7",
    en: "depart",
    vn: "khởi hành, rời đi",
  },
  {
    id: uuidv4(),
    sessionId: "unit7",
    en: "depress",
    vn: "làm chán nản, làm suy giảm",
  },
  {
    id: uuidv4(),
    sessionId: "unit7",
    en: "factual",
    vn: "dựa trên sự thật",
  },
  {
    id: uuidv4(),
    sessionId: "unit7",
    en: "fascinate",
    vn: "làm mê hoặc, cuốn hút",
  },
  {
    id: uuidv4(),
    sessionId: "unit7",
    en: "mission",
    vn: "nhiệm vụ, sứ mệnh",
  },
  {
    id: uuidv4(),
    sessionId: "unit7",
    en: "nevertheless",
    vn: "tuy nhiên, dù vậy",
  },
  {
    id: uuidv4(),
    sessionId: "unit7",
    en: "occupation",
    vn: "nghề nghiệp, sự chiếm đóng",
  },
  {
    id: uuidv4(),
    sessionId: "unit7",
    en: "overseas",
    vn: "nước ngoài, hải ngoại",
  },
  {
    id: uuidv4(),
    sessionId: "unit7",
    en: "persuade",
    vn: "thuyết phục",
  },
  {
    id: uuidv4(),
    sessionId: "unit7",
    en: "route",
    vn: "tuyến đường, lộ trình",
  },
  {
    id: uuidv4(),
    sessionId: "unit7",
    en: "ruins",
    vn: "tàn tích, đống đổ nát",
  },
  {
    id: uuidv4(),
    sessionId: "unit7",
    en: "scholar",
    vn: "học giả, nhà nghiên cứu",
  },
  {
    id: uuidv4(),
    sessionId: "unit7",
    en: "significant",
    vn: "quan trọng, đáng kể",
  },
  {
    id: uuidv4(),
    sessionId: "unit7",
    en: "volcano",
    vn: "núi lửa",
  },
  {
    id: uuidv4(),
    sessionId: "unit8",
    en: "broad",
    vn: "rộng, bao quát",
  },
  {
    id: uuidv4(),
    sessionId: "unit8",
    en: "bush",
    vn: "bụi cây",
  },
  {
    id: uuidv4(),
    sessionId: "unit8",
    en: "capable",
    vn: "có khả năng",
  },
  {
    id: uuidv4(),
    sessionId: "unit8",
    en: "cheat",
    vn: "gian lận",
  },
  {
    id: uuidv4(),
    sessionId: "unit8",
    en: "concentrate",
    vn: "tập trung",
  },
  {
    id: uuidv4(),
    sessionId: "unit8",
    en: "conclude",
    vn: "kết luận",
  },
  {
    id: uuidv4(),
    sessionId: "unit8",
    en: "confident",
    vn: "tự tin",
  },
  {
    id: uuidv4(),
    sessionId: "unit8",
    en: "considerable",
    vn: "đáng kể",
  },
  {
    id: uuidv4(),
    sessionId: "unit8",
    en: "convey",
    vn: "truyền đạt, chuyển tải",
  },
  {
    id: uuidv4(),
    sessionId: "unit8",
    en: "definite",
    vn: "chắc chắn, rõ ràng",
  },
  {
    id: uuidv4(),
    sessionId: "unit8",
    en: "delight",
    vn: "niềm vui, thích thú",
  },
  {
    id: uuidv4(),
    sessionId: "unit8",
    en: "destination",
    vn: "điểm đến",
  },
  {
    id: uuidv4(),
    sessionId: "unit8",
    en: "dictate",
    vn: "ra lệnh, đọc cho viết",
  },
  {
    id: uuidv4(),
    sessionId: "unit8",
    en: "edge",
    vn: "cạnh, bờ, mép",
  },
  {
    id: uuidv4(),
    sessionId: "unit8",
    en: "path",
    vn: "con đường, lối đi",
  },
  {
    id: uuidv4(),
    sessionId: "unit8",
    en: "resort",
    vn: "khu nghỉ dưỡng; dùng đến",
  },
  {
    id: uuidv4(),
    sessionId: "unit8",
    en: "shadow",
    vn: "bóng, bóng tối",
  },
  {
    id: uuidv4(),
    sessionId: "unit8",
    en: "succeed",
    vn: "thành công",
  },
  {
    id: uuidv4(),
    sessionId: "unit8",
    en: "suspect",
    vn: "nghi ngờ; kẻ tình nghi",
  },
  {
    id: uuidv4(),
    sessionId: "unit8",
    en: "valley",
    vn: "thung lũng",
  },
  { id: uuidv4(), sessionId: "unit9", en: "admire", vn: "ngưỡng mộ" },
  { id: uuidv4(), sessionId: "unit9", en: "aid", vn: "viện trợ, giúp đỡ" },
  { id: uuidv4(), sessionId: "unit9", en: "attempt", vn: "cố gắng, nỗ lực" },
  {
    id: uuidv4(),
    sessionId: "unit9",
    en: "authority",
    vn: "thẩm quyền, quyền lực",
  },
  { id: uuidv4(), sessionId: "unit9", en: "capital", vn: "thủ đô, vốn" },
  { id: uuidv4(), sessionId: "unit9", en: "cooperate", vn: "hợp tác" },
  { id: uuidv4(), sessionId: "unit9", en: "defend", vn: "bảo vệ, phòng thủ" },
  { id: uuidv4(), sessionId: "unit9", en: "destruction", vn: "sự phá hủy" },
  { id: uuidv4(), sessionId: "unit9", en: "disorder", vn: "rối loạn, lộn xộn" },
  { id: uuidv4(), sessionId: "unit9", en: "division", vn: "sự phân chia" },
  {
    id: uuidv4(),
    sessionId: "unit9",
    en: "enable",
    vn: "cho phép, làm cho có thể",
  },
  {
    id: uuidv4(),
    sessionId: "unit9",
    en: "frustrate",
    vn: "làm thất vọng, cản trở",
  },
  { id: uuidv4(), sessionId: "unit9", en: "govern", vn: "cai trị, quản lý" },
  { id: uuidv4(), sessionId: "unit9", en: "plenty", vn: "nhiều, dồi dào" },
  {
    id: uuidv4(),
    sessionId: "unit9",
    en: "relieve",
    vn: "làm dịu đi, giảm nhẹ",
  },
  { id: uuidv4(), sessionId: "unit9", en: "reputation", vn: "danh tiếng" },
  { id: uuidv4(), sessionId: "unit9", en: "royal", vn: "hoàng gia" },
  { id: uuidv4(), sessionId: "unit9", en: "slave", vn: "nô lệ" },
  {
    id: uuidv4(),
    sessionId: "unit9",
    en: "struggle",
    vn: "đấu tranh, vật lộn",
  },
  { id: uuidv4(), sessionId: "unit9", en: "stupid", vn: "ngu ngốc" },
  { id: uuidv4(), sessionId: "unit10", en: "citizen", vn: "công dân" },
  { id: uuidv4(), sessionId: "unit10", en: "council", vn: "hội đồng" },
  {
    id: uuidv4(),
    sessionId: "unit10",
    en: "declare",
    vn: "tuyên bố, khai báo",
  },
  { id: uuidv4(), sessionId: "unit10", en: "enormous", vn: "to lớn, khổng lồ" },
  {
    id: uuidv4(),
    sessionId: "unit10",
    en: "extraordinary",
    vn: "phi thường, đặc biệt",
  },
  { id: uuidv4(), sessionId: "unit10", en: "fog", vn: "sương mù" },
  { id: uuidv4(), sessionId: "unit10", en: "funeral", vn: "đám tang" },
  { id: uuidv4(), sessionId: "unit10", en: "giant", vn: "người khổng lồ" },
  { id: uuidv4(), sessionId: "unit10", en: "impression", vn: "ấn tượng" },
  { id: uuidv4(), sessionId: "unit10", en: "income", vn: "thu nhập" },
  { id: uuidv4(), sessionId: "unit10", en: "mad", vn: "điên, phát điên" },
  { id: uuidv4(), sessionId: "unit10", en: "ought", vn: "nên, phải" },
  {
    id: uuidv4(),
    sessionId: "unit10",
    en: "resist",
    vn: "chống lại, kháng cự",
  },
  { id: uuidv4(), sessionId: "unit10", en: "reveal", vn: "tiết lộ, bộc lộ" },
  { id: uuidv4(), sessionId: "unit10", en: "rid", vn: "loại bỏ" },
  { id: uuidv4(), sessionId: "unit10", en: "sword", vn: "thanh kiếm" },
  {
    id: uuidv4(),
    sessionId: "unit10",
    en: "tale",
    vn: "câu chuyện, truyện kể",
  },
  { id: uuidv4(), sessionId: "unit10", en: "trap", vn: "cái bẫy" },
  {
    id: uuidv4(),
    sessionId: "unit10",
    en: "trial",
    vn: "phiên tòa, thử nghiệm",
  },
  { id: uuidv4(), sessionId: "unit10", en: "violent", vn: "bạo lực, dữ dội" },
  {
    id: uuidv4(),
    sessionId: "unit11",
    en: "admission",
    vn: "sự nhận vào, sự thú nhận",
  },
  { id: uuidv4(), sessionId: "unit11", en: "astronomy", vn: "thiên văn học" },
  { id: uuidv4(), sessionId: "unit11", en: "blame", vn: "đổ lỗi, trách" },
  { id: uuidv4(), sessionId: "unit11", en: "chemistry", vn: "hóa học" },
  { id: uuidv4(), sessionId: "unit11", en: "despite", vn: "mặc dù" },
  { id: uuidv4(), sessionId: "unit11", en: "dinosaur", vn: "khủng long" },
  {
    id: uuidv4(),
    sessionId: "unit11",
    en: "exhibit",
    vn: "trưng bày, triển lãm",
  },
  { id: uuidv4(), sessionId: "unit11", en: "fame", vn: "danh tiếng" },
  { id: uuidv4(), sessionId: "unit11", en: "forecast", vn: "dự báo" },
  { id: uuidv4(), sessionId: "unit11", en: "genius", vn: "thiên tài" },
  {
    id: uuidv4(),
    sessionId: "unit11",
    en: "gentle",
    vn: "dịu dàng, nhẹ nhàng",
  },
  { id: uuidv4(), sessionId: "unit11", en: "geography", vn: "địa lý" },
  {
    id: uuidv4(),
    sessionId: "unit11",
    en: "interfere",
    vn: "can thiệp, xen vào",
  },
  { id: uuidv4(), sessionId: "unit11", en: "lightly", vn: "nhẹ nhàng" },
  {
    id: uuidv4(),
    sessionId: "unit11",
    en: "principal",
    vn: "hiệu trưởng, chính yếu",
  },
  { id: uuidv4(), sessionId: "unit11", en: "row", vn: "hàng, dãy; cãi nhau" },
  { id: uuidv4(), sessionId: "unit11", en: "shelf", vn: "kệ, giá" },
  { id: uuidv4(), sessionId: "unit11", en: "spite", vn: "sự thù hằn" },
  { id: uuidv4(), sessionId: "unit11", en: "super", vn: "tuyệt vời, siêu" },
  { id: uuidv4(), sessionId: "unit11", en: "wet", vn: "ướt" },
  { id: uuidv4(), sessionId: "unit12", en: "abuse", vn: "lạm dụng, ngược đãi" },
  {
    id: uuidv4(),
    sessionId: "unit12",
    en: "afford",
    vn: "có khả năng chi trả",
  },
  { id: uuidv4(), sessionId: "unit12", en: "bake", vn: "nướng (bánh, đồ ăn)" },
  { id: uuidv4(), sessionId: "unit12", en: "bean", vn: "hạt đậu" },
  { id: uuidv4(), sessionId: "unit12", en: "candle", vn: "cây nến" },
  { id: uuidv4(), sessionId: "unit12", en: "convert", vn: "chuyển đổi" },
  { id: uuidv4(), sessionId: "unit12", en: "debt", vn: "nợ nần" },
  { id: uuidv4(), sessionId: "unit12", en: "decrease", vn: "giảm, suy giảm" },
  { id: uuidv4(), sessionId: "unit12", en: "fault", vn: "lỗi, sai sót" },
  { id: uuidv4(), sessionId: "unit12", en: "fund", vn: "quỹ, cấp vốn" },
  { id: uuidv4(), sessionId: "unit12", en: "generous", vn: "hào phóng" },
  {
    id: uuidv4(),
    sessionId: "unit12",
    en: "ingredient",
    vn: "thành phần, nguyên liệu",
  },
  {
    id: uuidv4(),
    sessionId: "unit12",
    en: "insist",
    vn: "khăng khăng, nhấn mạnh",
  },
  { id: uuidv4(), sessionId: "unit12", en: "mess", vn: "mớ hỗn độn, lộn xộn" },
  { id: uuidv4(), sessionId: "unit12", en: "metal", vn: "kim loại" },
  {
    id: uuidv4(),
    sessionId: "unit12",
    en: "monitor",
    vn: "giám sát, màn hình",
  },
  { id: uuidv4(), sessionId: "unit12", en: "oppose", vn: "phản đối" },
  { id: uuidv4(), sessionId: "unit12", en: "passive", vn: "bị động" },
  { id: uuidv4(), sessionId: "unit12", en: "quantity", vn: "số lượng" },
  { id: uuidv4(), sessionId: "unit12", en: "sue", vn: "kiện, khởi kiện" },
  { id: uuidv4(), sessionId: "unit13", en: "anxiety", vn: "sự lo lắng, lo âu" },
  { id: uuidv4(), sessionId: "unit13", en: "army", vn: "quân đội" },
  { id: uuidv4(), sessionId: "unit13", en: "billion", vn: "tỷ" },
  { id: uuidv4(), sessionId: "unit13", en: "carve", vn: "chạm khắc, cắt tạc" },
  {
    id: uuidv4(),
    sessionId: "unit13",
    en: "consult",
    vn: "tham khảo, hỏi ý kiến",
  },
  {
    id: uuidv4(),
    sessionId: "unit13",
    en: "emergency",
    vn: "tình huống khẩn cấp",
  },
  {
    id: uuidv4(),
    sessionId: "unit13",
    en: "fortune",
    vn: "vận may, tài sản lớn",
  },
  {
    id: uuidv4(),
    sessionId: "unit13",
    en: "guarantee",
    vn: "đảm bảo, cam kết",
  },
  {
    id: uuidv4(),
    sessionId: "unit13",
    en: "hike",
    vn: "đi bộ đường dài, leo núi",
  },
  { id: uuidv4(), sessionId: "unit13", en: "initial", vn: "ban đầu" },
  { id: uuidv4(), sessionId: "unit13", en: "intense", vn: "mãnh liệt, dữ dội" },
  { id: uuidv4(), sessionId: "unit13", en: "lend", vn: "cho mượn, cho vay" },
  { id: uuidv4(), sessionId: "unit13", en: "peak", vn: "đỉnh, cao điểm" },
  { id: uuidv4(), sessionId: "unit13", en: "potential", vn: "tiềm năng" },
  { id: uuidv4(), sessionId: "unit13", en: "pride", vn: "niềm tự hào" },
  { id: uuidv4(), sessionId: "unit13", en: "proof", vn: "bằng chứng" },
  { id: uuidv4(), sessionId: "unit13", en: "quit", vn: "bỏ, nghỉ" },
  { id: uuidv4(), sessionId: "unit13", en: "spin", vn: "xoay tròn" },
  { id: uuidv4(), sessionId: "unit13", en: "tiny", vn: "nhỏ bé" },
  {
    id: uuidv4(),
    sessionId: "unit13",
    en: "tutor",
    vn: "gia sư, người dạy kèm",
  },
  {
    id: uuidv4(),
    sessionId: "unit14",
    en: "apparent",
    vn: "rõ ràng, hiển nhiên",
  },
  { id: uuidv4(), sessionId: "unit14", en: "blind", vn: "mù, không nhìn thấy" },
  { id: uuidv4(), sessionId: "unit14", en: "calculate", vn: "tính toán" },
  {
    id: uuidv4(),
    sessionId: "unit14",
    en: "chat",
    vn: "tán gẫu, nói chuyện phiếm",
  },
  {
    id: uuidv4(),
    sessionId: "unit14",
    en: "commit",
    vn: "cam kết, phạm (tội)",
  },
  { id: uuidv4(), sessionId: "unit14", en: "compose", vn: "sáng tác, soạn" },
  { id: uuidv4(), sessionId: "unit14", en: "dormitory", vn: "ký túc xá" },
  { id: uuidv4(), sessionId: "unit14", en: "exhaust", vn: "làm kiệt sức" },
  { id: uuidv4(), sessionId: "unit14", en: "greenhouse", vn: "nhà kính" },
  { id: uuidv4(), sessionId: "unit14", en: "ignore", vn: "phớt lờ, bỏ qua" },
  {
    id: uuidv4(),
    sessionId: "unit14",
    en: "obvious",
    vn: "rõ ràng, hiển nhiên",
  },
  { id: uuidv4(), sessionId: "unit14", en: "physics", vn: "vật lý học" },
  { id: uuidv4(), sessionId: "unit14", en: "portion", vn: "phần, khẩu phần" },
  { id: uuidv4(), sessionId: "unit14", en: "remind", vn: "nhắc nhở" },
  { id: uuidv4(), sessionId: "unit14", en: "secretary", vn: "thư ký" },
  {
    id: uuidv4(),
    sessionId: "unit14",
    en: "severe",
    vn: "nghiêm trọng, khắc nghiệt",
  },
  { id: uuidv4(), sessionId: "unit14", en: "talent", vn: "tài năng" },
  { id: uuidv4(), sessionId: "unit14", en: "thesis", vn: "luận văn, luận án" },
  { id: uuidv4(), sessionId: "unit14", en: "uniform", vn: "đồng phục" },
  { id: uuidv4(), sessionId: "unit14", en: "vision", vn: "tầm nhìn, thị giác" },
  { id: uuidv4(), sessionId: "unit15", en: "absorb", vn: "hấp thụ" },
  { id: uuidv4(), sessionId: "unit15", en: "boss", vn: "ông chủ, sếp" },
  { id: uuidv4(), sessionId: "unit15", en: "committee", vn: "ủy ban" },
  { id: uuidv4(), sessionId: "unit15", en: "contract", vn: "hợp đồng" },
  { id: uuidv4(), sessionId: "unit15", en: "crew", vn: "thủy thủ đoàn, đội" },
  {
    id: uuidv4(),
    sessionId: "unit15",
    en: "devote",
    vn: "cống hiến, dành cho",
  },
  { id: uuidv4(), sessionId: "unit15", en: "dig", vn: "đào" },
  { id: uuidv4(), sessionId: "unit15", en: "dine", vn: "ăn tối" },
  { id: uuidv4(), sessionId: "unit15", en: "donate", vn: "quyên góp" },
  { id: uuidv4(), sessionId: "unit15", en: "double", vn: "gấp đôi" },
  {
    id: uuidv4(),
    sessionId: "unit15",
    en: "elevate",
    vn: "nâng lên, nâng cao",
  },
  { id: uuidv4(), sessionId: "unit15", en: "flavor", vn: "hương vị" },
  {
    id: uuidv4(),
    sessionId: "unit15",
    en: "foundation",
    vn: "nền tảng, cơ sở",
  },
  { id: uuidv4(), sessionId: "unit15", en: "generation", vn: "thế hệ" },
  { id: uuidv4(), sessionId: "unit15", en: "handle", vn: "xử lý, tay cầm" },
  { id: uuidv4(), sessionId: "unit15", en: "layer", vn: "lớp, tầng" },
  { id: uuidv4(), sessionId: "unit15", en: "mud", vn: "bùn" },
  { id: uuidv4(), sessionId: "unit15", en: "smooth", vn: "mịn, trơn tru" },
  { id: uuidv4(), sessionId: "unit15", en: "soil", vn: "đất" },
  { id: uuidv4(), sessionId: "unit15", en: "unique", vn: "độc đáo, duy nhất" },
];
